// @generated by scripts/generate_mutation_value_codecs.py; DO NOT EDIT.
// source: docs/spec/SSMC1_EPOCH1_SCHEMA.txt; blake3-256: 1983bc8d6ad9ac3cb5390853f43959cf2c3dc0ae8e0ca18ca8264ca4960133ae

/// BLAKE3-256 of the exact canonical schema manifest used for host values.
pub const VALUE_HOST_SOURCE_SCHEMA_BLAKE3: [u8; 32] = [0x19, 0x83, 0xbc, 0x8d, 0x6a, 0xd9, 0xac, 0x3c, 0xb5, 0x39, 0x08, 0x53, 0xf4, 0x39, 0x59, 0xcf, 0x2c, 0x3d, 0xc0, 0xae, 0x8e, 0x0c, 0xa1, 0x8c, 0xa8, 0x26, 0x4c, 0xa4, 0x96, 0x01, 0x33, 0xae];
/// Closed entity-body host-value count.
pub const ENTITY_BODY_VALUE_COUNT: usize = 18;
/// Closed entity-body field-value count.
pub const FIELD_VALUE_COUNT: usize = 75;
/// Exact immutable descriptor-to-typed-value binding count.
pub const TYPED_VALUE_BINDING_COUNT: usize = 179;

/// Closed proposal-only body for entity kind 1 (`Workspace`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WorkspaceBody {
    /// Exact manifest field 1 (`packages`).
    pub packages: EntityIdSet,
    /// Exact manifest field 2 (`root_namespace`).
    pub root_namespace: EntityId,
    /// Exact manifest field 3 (`capability_requirements`).
    pub capability_requirements: EntityIdSet,
    /// Exact manifest field 4 (`contracts`).
    pub contracts: EntityIdSet,
    /// Exact manifest field 5 (`tests`).
    pub tests: EntityIdSet,
}

/// Closed proposal-only body for entity kind 2 (`Package`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PackageBody {
    /// Exact manifest field 1 (`workspace`).
    pub workspace: EntityId,
    /// Exact manifest field 2 (`root_namespace`).
    pub root_namespace: EntityId,
    /// Exact manifest field 3 (`dependencies`).
    pub dependencies: EntityIdSet,
    /// Exact manifest field 4 (`exports`).
    pub exports: EntityIdSet,
}

/// Closed proposal-only body for entity kind 3 (`Namespace`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NamespaceBody {
    /// Exact manifest field 1 (`parent`).
    pub parent: Option<EntityId>,
    /// Exact manifest field 2 (`members`).
    pub members: EntityIdSet,
}

/// Closed proposal-only body for entity kind 4 (`TypeDef`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TypeDefBody {
    /// Exact manifest field 1 (`type_parameters`).
    pub type_parameters: Vec<sley_ssmc::TypeParameterDef>,
    /// Exact manifest field 2 (`form`).
    pub form: sley_ssmc::TypeDefForm,
    /// Exact manifest field 3 (`invariants`).
    pub invariants: EntityIdSet,
    /// Exact manifest field 4 (`visibility`).
    pub visibility: sley_ssmc::Visibility,
}

/// Closed proposal-only body for entity kind 5 (`Function`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct FunctionBody {
    /// Exact manifest field 1 (`type_parameters`).
    pub type_parameters: Vec<sley_ssmc::TypeParameterDef>,
    /// Exact manifest field 2 (`parameters`).
    pub parameters: Vec<EntityId>,
    /// Exact manifest field 3 (`result_type`).
    pub result_type: sley_ssmc::TypeExpr,
    /// Exact manifest field 4 (`effects`).
    pub effects: EntityIdSet,
    /// Exact manifest field 5 (`entry_block`).
    pub entry_block: EntityId,
    /// Exact manifest field 6 (`blocks`).
    pub blocks: Vec<EntityId>,
    /// Exact manifest field 7 (`contracts`).
    pub contracts: EntityIdSet,
    /// Exact manifest field 8 (`visibility`).
    pub visibility: sley_ssmc::Visibility,
}

/// Closed proposal-only body for entity kind 6 (`Parameter`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ParameterBody {
    /// Exact manifest field 1 (`owner`).
    pub owner: EntityId,
    /// Exact manifest field 2 (`role`).
    pub role: sley_ssmc::ParameterRole,
    /// Exact manifest field 3 (`ordinal`).
    pub ordinal: u32,
    /// Exact manifest field 4 (`value_type`).
    pub value_type: sley_ssmc::TypeExpr,
}

/// Closed proposal-only body for entity kind 7 (`Block`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct BlockBody {
    /// Exact manifest field 1 (`function`).
    pub function: EntityId,
    /// Exact manifest field 2 (`parameters`).
    pub parameters: Vec<EntityId>,
    /// Exact manifest field 3 (`operations`).
    pub operations: Vec<EntityId>,
    /// Exact manifest field 4 (`terminator`).
    pub terminator: sley_ssmc::Terminator,
    /// Exact manifest field 5 (`reachability`).
    pub reachability: sley_ssmc::Reachability,
}

/// Closed proposal-only body for entity kind 8 (`Operation`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OperationBody {
    /// Exact manifest field 1 (`block`).
    pub block: EntityId,
    /// Exact manifest field 2 (`ordinal`).
    pub ordinal: u32,
    /// Exact manifest field 3 (`opcode`).
    pub opcode: u32,
    /// Exact manifest field 4 (`operands`).
    pub operands: Vec<sley_ssmc::ValueRef>,
    /// Exact manifest field 5 (`result_types`).
    pub result_types: Vec<sley_ssmc::TypeExpr>,
    /// Exact manifest field 6 (`immediate`).
    pub immediate: sley_ssmc::Immediate,
}

/// Closed proposal-only body for entity kind 9 (`Constant`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ConstantBody {
    /// Exact manifest field 1 (`value`).
    pub value: sley_ssmc::ConstValue,
}

/// Closed proposal-only body for entity kind 10 (`GlobalValue`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GlobalValueBody {
    /// Exact manifest field 1 (`value_type`).
    pub value_type: sley_ssmc::TypeExpr,
    /// Exact manifest field 2 (`initializer`).
    pub initializer: EntityId,
    /// Exact manifest field 3 (`visibility`).
    pub visibility: sley_ssmc::Visibility,
}

/// Closed proposal-only body for entity kind 11 (`EffectDef`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EffectDefBody {
    /// Exact manifest field 1 (`effect_kind`).
    pub effect_kind: sley_ssmc::EffectKind,
    /// Exact manifest field 2 (`scope_type`).
    pub scope_type: sley_ssmc::TypeExpr,
    /// Exact manifest field 3 (`request_type`).
    pub request_type: sley_ssmc::TypeExpr,
    /// Exact manifest field 4 (`response_type`).
    pub response_type: sley_ssmc::TypeExpr,
    /// Exact manifest field 5 (`failure_type`).
    pub failure_type: sley_ssmc::TypeExpr,
    /// Exact manifest field 6 (`visibility`).
    pub visibility: sley_ssmc::Visibility,
}

/// Closed proposal-only body for entity kind 12 (`CapabilityRequirement`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CapabilityRequirementBody {
    /// Exact manifest field 1 (`effect`).
    pub effect: EntityId,
    /// Exact manifest field 2 (`allowed_scopes`).
    pub allowed_scopes: Vec<sley_ssmc::ConstValue>,
    /// Exact manifest field 3 (`constraint_contracts`).
    pub constraint_contracts: EntityIdSet,
}

/// Closed proposal-only body for entity kind 13 (`Contract`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ContractBody {
    /// Exact manifest field 1 (`target`).
    pub target: EntityId,
    /// Exact manifest field 2 (`contract_kind`).
    pub contract_kind: sley_ssmc::ContractKind,
    /// Exact manifest field 3 (`predicate`).
    pub predicate: EntityId,
    /// Exact manifest field 4 (`bindings`).
    pub bindings: Vec<sley_ssmc::ContractBinding>,
    /// Exact manifest field 5 (`resource_limits`).
    pub resource_limits: Option<sley_ssmc::ResourceLimits>,
}

/// Closed proposal-only body for entity kind 14 (`TestCase`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TestCaseBody {
    /// Exact manifest field 1 (`target`).
    pub target: EntityId,
    /// Exact manifest field 2 (`inputs`).
    pub inputs: Vec<sley_ssmc::ConstValue>,
    /// Exact manifest field 3 (`effect_environment`).
    pub effect_environment: sley_ssmc::EffectEnvironment,
    /// Exact manifest field 4 (`expected`).
    pub expected: sley_ssmc::ExpectedOutcome,
    /// Exact manifest field 5 (`observations`).
    pub observations: Vec<sley_ssmc::ExpectedObservation>,
    /// Exact manifest field 6 (`resource_limits`).
    pub resource_limits: sley_ssmc::ResourceLimits,
}

/// Closed proposal-only body for entity kind 15 (`AdapterImport`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AdapterImportBody {
    /// Exact manifest field 1 (`adapter_id`).
    pub adapter_id: [u8; 32],
    /// Exact manifest field 2 (`abi_version`).
    pub abi_version: u32,
    /// Exact manifest field 3 (`request_type`).
    pub request_type: sley_ssmc::TypeExpr,
    /// Exact manifest field 4 (`response_type`).
    pub response_type: sley_ssmc::TypeExpr,
    /// Exact manifest field 5 (`failure_type`).
    pub failure_type: sley_ssmc::TypeExpr,
    /// Exact manifest field 6 (`effects`).
    pub effects: EntityIdSet,
}

/// Closed proposal-only body for entity kind 16 (`EntryPoint`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EntryPointBody {
    /// Exact manifest field 1 (`function`).
    pub function: EntityId,
    /// Exact manifest field 2 (`exposure`).
    pub exposure: EntryExposure,
}

/// Closed proposal-only body for entity kind 17 (`PolicyBinding`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PolicyBindingBody {
    /// Exact manifest field 1 (`subject`).
    pub subject: EntityId,
    /// Exact manifest field 2 (`requirements`).
    pub requirements: EntityIdSet,
}

/// Closed proposal-only body for entity kind 18 (`DependencyBinding`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DependencyBindingBody {
    /// Exact manifest field 1 (`dependency_root`).
    pub dependency_root: StateRoot,
    /// Exact manifest field 2 (`external_package`).
    pub external_package: EntityId,
    /// Exact manifest field 3 (`local_namespace`).
    pub local_namespace: EntityId,
}

/// Closed discriminant for one complete SSMC1 entity-body value.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum EntityBodyValueKind {
    /// Entity kind 1 (`Workspace`).
    Workspace,
    /// Entity kind 2 (`Package`).
    Package,
    /// Entity kind 3 (`Namespace`).
    Namespace,
    /// Entity kind 4 (`TypeDef`).
    TypeDef,
    /// Entity kind 5 (`Function`).
    Function,
    /// Entity kind 6 (`Parameter`).
    Parameter,
    /// Entity kind 7 (`Block`).
    Block,
    /// Entity kind 8 (`Operation`).
    Operation,
    /// Entity kind 9 (`Constant`).
    Constant,
    /// Entity kind 10 (`GlobalValue`).
    GlobalValue,
    /// Entity kind 11 (`EffectDef`).
    EffectDef,
    /// Entity kind 12 (`CapabilityRequirement`).
    CapabilityRequirement,
    /// Entity kind 13 (`Contract`).
    Contract,
    /// Entity kind 14 (`TestCase`).
    TestCase,
    /// Entity kind 15 (`AdapterImport`).
    AdapterImport,
    /// Entity kind 16 (`EntryPoint`).
    EntryPoint,
    /// Entity kind 17 (`PolicyBinding`).
    PolicyBinding,
    /// Entity kind 18 (`DependencyBinding`).
    DependencyBinding,
}

impl EntityBodyValueKind {
    /// Returns the exact closed SSMC1 entity-kind tag.
    #[must_use]
    pub const fn kind_tag(self) -> u16 {
        match self {
            Self::Workspace => 1,
            Self::Package => 2,
            Self::Namespace => 3,
            Self::TypeDef => 4,
            Self::Function => 5,
            Self::Parameter => 6,
            Self::Block => 7,
            Self::Operation => 8,
            Self::Constant => 9,
            Self::GlobalValue => 10,
            Self::EffectDef => 11,
            Self::CapabilityRequirement => 12,
            Self::Contract => 13,
            Self::TestCase => 14,
            Self::AdapterImport => 15,
            Self::EntryPoint => 16,
            Self::PolicyBinding => 17,
            Self::DependencyBinding => 18,
        }
    }
}

/// Closed typed value for one complete SSMC1 entity body.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum EntityBodyValue {
    /// Entity kind 1 (`Workspace`).
    Workspace(WorkspaceBody),
    /// Entity kind 2 (`Package`).
    Package(PackageBody),
    /// Entity kind 3 (`Namespace`).
    Namespace(NamespaceBody),
    /// Entity kind 4 (`TypeDef`).
    TypeDef(TypeDefBody),
    /// Entity kind 5 (`Function`).
    Function(FunctionBody),
    /// Entity kind 6 (`Parameter`).
    Parameter(ParameterBody),
    /// Entity kind 7 (`Block`).
    Block(BlockBody),
    /// Entity kind 8 (`Operation`).
    Operation(OperationBody),
    /// Entity kind 9 (`Constant`).
    Constant(ConstantBody),
    /// Entity kind 10 (`GlobalValue`).
    GlobalValue(GlobalValueBody),
    /// Entity kind 11 (`EffectDef`).
    EffectDef(EffectDefBody),
    /// Entity kind 12 (`CapabilityRequirement`).
    CapabilityRequirement(CapabilityRequirementBody),
    /// Entity kind 13 (`Contract`).
    Contract(ContractBody),
    /// Entity kind 14 (`TestCase`).
    TestCase(TestCaseBody),
    /// Entity kind 15 (`AdapterImport`).
    AdapterImport(AdapterImportBody),
    /// Entity kind 16 (`EntryPoint`).
    EntryPoint(EntryPointBody),
    /// Entity kind 17 (`PolicyBinding`).
    PolicyBinding(PolicyBindingBody),
    /// Entity kind 18 (`DependencyBinding`).
    DependencyBinding(DependencyBindingBody),
}

impl EntityBodyValue {
    /// Returns the exact closed body-value discriminant.
    #[must_use]
    pub const fn value_kind(&self) -> EntityBodyValueKind {
        match self {
            Self::Workspace(..) => EntityBodyValueKind::Workspace,
            Self::Package(..) => EntityBodyValueKind::Package,
            Self::Namespace(..) => EntityBodyValueKind::Namespace,
            Self::TypeDef(..) => EntityBodyValueKind::TypeDef,
            Self::Function(..) => EntityBodyValueKind::Function,
            Self::Parameter(..) => EntityBodyValueKind::Parameter,
            Self::Block(..) => EntityBodyValueKind::Block,
            Self::Operation(..) => EntityBodyValueKind::Operation,
            Self::Constant(..) => EntityBodyValueKind::Constant,
            Self::GlobalValue(..) => EntityBodyValueKind::GlobalValue,
            Self::EffectDef(..) => EntityBodyValueKind::EffectDef,
            Self::CapabilityRequirement(..) => EntityBodyValueKind::CapabilityRequirement,
            Self::Contract(..) => EntityBodyValueKind::Contract,
            Self::TestCase(..) => EntityBodyValueKind::TestCase,
            Self::AdapterImport(..) => EntityBodyValueKind::AdapterImport,
            Self::EntryPoint(..) => EntityBodyValueKind::EntryPoint,
            Self::PolicyBinding(..) => EntityBodyValueKind::PolicyBinding,
            Self::DependencyBinding(..) => EntityBodyValueKind::DependencyBinding,
        }
    }

    /// Returns the exact closed SSMC1 entity-kind tag.
    #[must_use]
    pub const fn kind_tag(&self) -> u16 {
        self.value_kind().kind_tag()
    }
}

/// Closed discriminant for one exact SSMC1 entity-body field value.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum FieldValueKind {
    /// Kind 1, field 1 (`Workspace.packages`).
    WorkspacePackages,
    /// Kind 1, field 2 (`Workspace.root_namespace`).
    WorkspaceRootNamespace,
    /// Kind 1, field 3 (`Workspace.capability_requirements`).
    WorkspaceCapabilityRequirements,
    /// Kind 1, field 4 (`Workspace.contracts`).
    WorkspaceContracts,
    /// Kind 1, field 5 (`Workspace.tests`).
    WorkspaceTests,
    /// Kind 2, field 1 (`Package.workspace`).
    PackageWorkspace,
    /// Kind 2, field 2 (`Package.root_namespace`).
    PackageRootNamespace,
    /// Kind 2, field 3 (`Package.dependencies`).
    PackageDependencies,
    /// Kind 2, field 4 (`Package.exports`).
    PackageExports,
    /// Kind 3, field 1 (`Namespace.parent`).
    NamespaceParent,
    /// Kind 3, field 2 (`Namespace.members`).
    NamespaceMembers,
    /// Kind 4, field 1 (`TypeDef.type_parameters`).
    TypeDefTypeParameters,
    /// Kind 4, field 2 (`TypeDef.form`).
    TypeDefForm,
    /// Kind 4, field 3 (`TypeDef.invariants`).
    TypeDefInvariants,
    /// Kind 4, field 4 (`TypeDef.visibility`).
    TypeDefVisibility,
    /// Kind 5, field 1 (`Function.type_parameters`).
    FunctionTypeParameters,
    /// Kind 5, field 2 (`Function.parameters`).
    FunctionParameters,
    /// Kind 5, field 3 (`Function.result_type`).
    FunctionResultType,
    /// Kind 5, field 4 (`Function.effects`).
    FunctionEffects,
    /// Kind 5, field 5 (`Function.entry_block`).
    FunctionEntryBlock,
    /// Kind 5, field 6 (`Function.blocks`).
    FunctionBlocks,
    /// Kind 5, field 7 (`Function.contracts`).
    FunctionContracts,
    /// Kind 5, field 8 (`Function.visibility`).
    FunctionVisibility,
    /// Kind 6, field 1 (`Parameter.owner`).
    ParameterOwner,
    /// Kind 6, field 2 (`Parameter.role`).
    ParameterRole,
    /// Kind 6, field 3 (`Parameter.ordinal`).
    ParameterOrdinal,
    /// Kind 6, field 4 (`Parameter.value_type`).
    ParameterValueType,
    /// Kind 7, field 1 (`Block.function`).
    BlockFunction,
    /// Kind 7, field 2 (`Block.parameters`).
    BlockParameters,
    /// Kind 7, field 3 (`Block.operations`).
    BlockOperations,
    /// Kind 7, field 4 (`Block.terminator`).
    BlockTerminator,
    /// Kind 7, field 5 (`Block.reachability`).
    BlockReachability,
    /// Kind 8, field 1 (`Operation.block`).
    OperationBlock,
    /// Kind 8, field 2 (`Operation.ordinal`).
    OperationOrdinal,
    /// Kind 8, field 3 (`Operation.opcode`).
    OperationOpcode,
    /// Kind 8, field 4 (`Operation.operands`).
    OperationOperands,
    /// Kind 8, field 5 (`Operation.result_types`).
    OperationResultTypes,
    /// Kind 8, field 6 (`Operation.immediate`).
    OperationImmediate,
    /// Kind 9, field 1 (`Constant.value`).
    ConstantValue,
    /// Kind 10, field 1 (`GlobalValue.value_type`).
    GlobalValueValueType,
    /// Kind 10, field 2 (`GlobalValue.initializer`).
    GlobalValueInitializer,
    /// Kind 10, field 3 (`GlobalValue.visibility`).
    GlobalValueVisibility,
    /// Kind 11, field 1 (`EffectDef.effect_kind`).
    EffectDefEffectKind,
    /// Kind 11, field 2 (`EffectDef.scope_type`).
    EffectDefScopeType,
    /// Kind 11, field 3 (`EffectDef.request_type`).
    EffectDefRequestType,
    /// Kind 11, field 4 (`EffectDef.response_type`).
    EffectDefResponseType,
    /// Kind 11, field 5 (`EffectDef.failure_type`).
    EffectDefFailureType,
    /// Kind 11, field 6 (`EffectDef.visibility`).
    EffectDefVisibility,
    /// Kind 12, field 1 (`CapabilityRequirement.effect`).
    CapabilityRequirementEffect,
    /// Kind 12, field 2 (`CapabilityRequirement.allowed_scopes`).
    CapabilityRequirementAllowedScopes,
    /// Kind 12, field 3 (`CapabilityRequirement.constraint_contracts`).
    CapabilityRequirementConstraintContracts,
    /// Kind 13, field 1 (`Contract.target`).
    ContractTarget,
    /// Kind 13, field 2 (`Contract.contract_kind`).
    ContractContractKind,
    /// Kind 13, field 3 (`Contract.predicate`).
    ContractPredicate,
    /// Kind 13, field 4 (`Contract.bindings`).
    ContractBindings,
    /// Kind 13, field 5 (`Contract.resource_limits`).
    ContractResourceLimits,
    /// Kind 14, field 1 (`TestCase.target`).
    TestCaseTarget,
    /// Kind 14, field 2 (`TestCase.inputs`).
    TestCaseInputs,
    /// Kind 14, field 3 (`TestCase.effect_environment`).
    TestCaseEffectEnvironment,
    /// Kind 14, field 4 (`TestCase.expected`).
    TestCaseExpected,
    /// Kind 14, field 5 (`TestCase.observations`).
    TestCaseObservations,
    /// Kind 14, field 6 (`TestCase.resource_limits`).
    TestCaseResourceLimits,
    /// Kind 15, field 1 (`AdapterImport.adapter_id`).
    AdapterImportAdapterId,
    /// Kind 15, field 2 (`AdapterImport.abi_version`).
    AdapterImportAbiVersion,
    /// Kind 15, field 3 (`AdapterImport.request_type`).
    AdapterImportRequestType,
    /// Kind 15, field 4 (`AdapterImport.response_type`).
    AdapterImportResponseType,
    /// Kind 15, field 5 (`AdapterImport.failure_type`).
    AdapterImportFailureType,
    /// Kind 15, field 6 (`AdapterImport.effects`).
    AdapterImportEffects,
    /// Kind 16, field 1 (`EntryPoint.function`).
    EntryPointFunction,
    /// Kind 16, field 2 (`EntryPoint.exposure`).
    EntryPointExposure,
    /// Kind 17, field 1 (`PolicyBinding.subject`).
    PolicyBindingSubject,
    /// Kind 17, field 2 (`PolicyBinding.requirements`).
    PolicyBindingRequirements,
    /// Kind 18, field 1 (`DependencyBinding.dependency_root`).
    DependencyBindingDependencyRoot,
    /// Kind 18, field 2 (`DependencyBinding.external_package`).
    DependencyBindingExternalPackage,
    /// Kind 18, field 3 (`DependencyBinding.local_namespace`).
    DependencyBindingLocalNamespace,
}

impl FieldValueKind {
    /// Returns the exact `(entity_kind, field_tag)` selected by this discriminant.
    #[must_use]
    pub const fn field_key(self) -> (u16, u16) {
        match self {
            Self::WorkspacePackages => (1, 1),
            Self::WorkspaceRootNamespace => (1, 2),
            Self::WorkspaceCapabilityRequirements => (1, 3),
            Self::WorkspaceContracts => (1, 4),
            Self::WorkspaceTests => (1, 5),
            Self::PackageWorkspace => (2, 1),
            Self::PackageRootNamespace => (2, 2),
            Self::PackageDependencies => (2, 3),
            Self::PackageExports => (2, 4),
            Self::NamespaceParent => (3, 1),
            Self::NamespaceMembers => (3, 2),
            Self::TypeDefTypeParameters => (4, 1),
            Self::TypeDefForm => (4, 2),
            Self::TypeDefInvariants => (4, 3),
            Self::TypeDefVisibility => (4, 4),
            Self::FunctionTypeParameters => (5, 1),
            Self::FunctionParameters => (5, 2),
            Self::FunctionResultType => (5, 3),
            Self::FunctionEffects => (5, 4),
            Self::FunctionEntryBlock => (5, 5),
            Self::FunctionBlocks => (5, 6),
            Self::FunctionContracts => (5, 7),
            Self::FunctionVisibility => (5, 8),
            Self::ParameterOwner => (6, 1),
            Self::ParameterRole => (6, 2),
            Self::ParameterOrdinal => (6, 3),
            Self::ParameterValueType => (6, 4),
            Self::BlockFunction => (7, 1),
            Self::BlockParameters => (7, 2),
            Self::BlockOperations => (7, 3),
            Self::BlockTerminator => (7, 4),
            Self::BlockReachability => (7, 5),
            Self::OperationBlock => (8, 1),
            Self::OperationOrdinal => (8, 2),
            Self::OperationOpcode => (8, 3),
            Self::OperationOperands => (8, 4),
            Self::OperationResultTypes => (8, 5),
            Self::OperationImmediate => (8, 6),
            Self::ConstantValue => (9, 1),
            Self::GlobalValueValueType => (10, 1),
            Self::GlobalValueInitializer => (10, 2),
            Self::GlobalValueVisibility => (10, 3),
            Self::EffectDefEffectKind => (11, 1),
            Self::EffectDefScopeType => (11, 2),
            Self::EffectDefRequestType => (11, 3),
            Self::EffectDefResponseType => (11, 4),
            Self::EffectDefFailureType => (11, 5),
            Self::EffectDefVisibility => (11, 6),
            Self::CapabilityRequirementEffect => (12, 1),
            Self::CapabilityRequirementAllowedScopes => (12, 2),
            Self::CapabilityRequirementConstraintContracts => (12, 3),
            Self::ContractTarget => (13, 1),
            Self::ContractContractKind => (13, 2),
            Self::ContractPredicate => (13, 3),
            Self::ContractBindings => (13, 4),
            Self::ContractResourceLimits => (13, 5),
            Self::TestCaseTarget => (14, 1),
            Self::TestCaseInputs => (14, 2),
            Self::TestCaseEffectEnvironment => (14, 3),
            Self::TestCaseExpected => (14, 4),
            Self::TestCaseObservations => (14, 5),
            Self::TestCaseResourceLimits => (14, 6),
            Self::AdapterImportAdapterId => (15, 1),
            Self::AdapterImportAbiVersion => (15, 2),
            Self::AdapterImportRequestType => (15, 3),
            Self::AdapterImportResponseType => (15, 4),
            Self::AdapterImportFailureType => (15, 5),
            Self::AdapterImportEffects => (15, 6),
            Self::EntryPointFunction => (16, 1),
            Self::EntryPointExposure => (16, 2),
            Self::PolicyBindingSubject => (17, 1),
            Self::PolicyBindingRequirements => (17, 2),
            Self::DependencyBindingDependencyRoot => (18, 1),
            Self::DependencyBindingExternalPackage => (18, 2),
            Self::DependencyBindingLocalNamespace => (18, 3),
        }
    }
}

/// Closed typed value for one exact SSMC1 entity-body field.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum FieldValue {
    /// Kind 1, field 1 (`Workspace.packages`).
    WorkspacePackages(EntityIdSet),
    /// Kind 1, field 2 (`Workspace.root_namespace`).
    WorkspaceRootNamespace(EntityId),
    /// Kind 1, field 3 (`Workspace.capability_requirements`).
    WorkspaceCapabilityRequirements(EntityIdSet),
    /// Kind 1, field 4 (`Workspace.contracts`).
    WorkspaceContracts(EntityIdSet),
    /// Kind 1, field 5 (`Workspace.tests`).
    WorkspaceTests(EntityIdSet),
    /// Kind 2, field 1 (`Package.workspace`).
    PackageWorkspace(EntityId),
    /// Kind 2, field 2 (`Package.root_namespace`).
    PackageRootNamespace(EntityId),
    /// Kind 2, field 3 (`Package.dependencies`).
    PackageDependencies(EntityIdSet),
    /// Kind 2, field 4 (`Package.exports`).
    PackageExports(EntityIdSet),
    /// Kind 3, field 1 (`Namespace.parent`).
    NamespaceParent(Option<EntityId>),
    /// Kind 3, field 2 (`Namespace.members`).
    NamespaceMembers(EntityIdSet),
    /// Kind 4, field 1 (`TypeDef.type_parameters`).
    TypeDefTypeParameters(Vec<sley_ssmc::TypeParameterDef>),
    /// Kind 4, field 2 (`TypeDef.form`).
    TypeDefForm(sley_ssmc::TypeDefForm),
    /// Kind 4, field 3 (`TypeDef.invariants`).
    TypeDefInvariants(EntityIdSet),
    /// Kind 4, field 4 (`TypeDef.visibility`).
    TypeDefVisibility(sley_ssmc::Visibility),
    /// Kind 5, field 1 (`Function.type_parameters`).
    FunctionTypeParameters(Vec<sley_ssmc::TypeParameterDef>),
    /// Kind 5, field 2 (`Function.parameters`).
    FunctionParameters(Vec<EntityId>),
    /// Kind 5, field 3 (`Function.result_type`).
    FunctionResultType(sley_ssmc::TypeExpr),
    /// Kind 5, field 4 (`Function.effects`).
    FunctionEffects(EntityIdSet),
    /// Kind 5, field 5 (`Function.entry_block`).
    FunctionEntryBlock(EntityId),
    /// Kind 5, field 6 (`Function.blocks`).
    FunctionBlocks(Vec<EntityId>),
    /// Kind 5, field 7 (`Function.contracts`).
    FunctionContracts(EntityIdSet),
    /// Kind 5, field 8 (`Function.visibility`).
    FunctionVisibility(sley_ssmc::Visibility),
    /// Kind 6, field 1 (`Parameter.owner`).
    ParameterOwner(EntityId),
    /// Kind 6, field 2 (`Parameter.role`).
    ParameterRole(sley_ssmc::ParameterRole),
    /// Kind 6, field 3 (`Parameter.ordinal`).
    ParameterOrdinal(u32),
    /// Kind 6, field 4 (`Parameter.value_type`).
    ParameterValueType(sley_ssmc::TypeExpr),
    /// Kind 7, field 1 (`Block.function`).
    BlockFunction(EntityId),
    /// Kind 7, field 2 (`Block.parameters`).
    BlockParameters(Vec<EntityId>),
    /// Kind 7, field 3 (`Block.operations`).
    BlockOperations(Vec<EntityId>),
    /// Kind 7, field 4 (`Block.terminator`).
    BlockTerminator(sley_ssmc::Terminator),
    /// Kind 7, field 5 (`Block.reachability`).
    BlockReachability(sley_ssmc::Reachability),
    /// Kind 8, field 1 (`Operation.block`).
    OperationBlock(EntityId),
    /// Kind 8, field 2 (`Operation.ordinal`).
    OperationOrdinal(u32),
    /// Kind 8, field 3 (`Operation.opcode`).
    OperationOpcode(u32),
    /// Kind 8, field 4 (`Operation.operands`).
    OperationOperands(Vec<sley_ssmc::ValueRef>),
    /// Kind 8, field 5 (`Operation.result_types`).
    OperationResultTypes(Vec<sley_ssmc::TypeExpr>),
    /// Kind 8, field 6 (`Operation.immediate`).
    OperationImmediate(sley_ssmc::Immediate),
    /// Kind 9, field 1 (`Constant.value`).
    ConstantValue(sley_ssmc::ConstValue),
    /// Kind 10, field 1 (`GlobalValue.value_type`).
    GlobalValueValueType(sley_ssmc::TypeExpr),
    /// Kind 10, field 2 (`GlobalValue.initializer`).
    GlobalValueInitializer(EntityId),
    /// Kind 10, field 3 (`GlobalValue.visibility`).
    GlobalValueVisibility(sley_ssmc::Visibility),
    /// Kind 11, field 1 (`EffectDef.effect_kind`).
    EffectDefEffectKind(sley_ssmc::EffectKind),
    /// Kind 11, field 2 (`EffectDef.scope_type`).
    EffectDefScopeType(sley_ssmc::TypeExpr),
    /// Kind 11, field 3 (`EffectDef.request_type`).
    EffectDefRequestType(sley_ssmc::TypeExpr),
    /// Kind 11, field 4 (`EffectDef.response_type`).
    EffectDefResponseType(sley_ssmc::TypeExpr),
    /// Kind 11, field 5 (`EffectDef.failure_type`).
    EffectDefFailureType(sley_ssmc::TypeExpr),
    /// Kind 11, field 6 (`EffectDef.visibility`).
    EffectDefVisibility(sley_ssmc::Visibility),
    /// Kind 12, field 1 (`CapabilityRequirement.effect`).
    CapabilityRequirementEffect(EntityId),
    /// Kind 12, field 2 (`CapabilityRequirement.allowed_scopes`).
    CapabilityRequirementAllowedScopes(Vec<sley_ssmc::ConstValue>),
    /// Kind 12, field 3 (`CapabilityRequirement.constraint_contracts`).
    CapabilityRequirementConstraintContracts(EntityIdSet),
    /// Kind 13, field 1 (`Contract.target`).
    ContractTarget(EntityId),
    /// Kind 13, field 2 (`Contract.contract_kind`).
    ContractContractKind(sley_ssmc::ContractKind),
    /// Kind 13, field 3 (`Contract.predicate`).
    ContractPredicate(EntityId),
    /// Kind 13, field 4 (`Contract.bindings`).
    ContractBindings(Vec<sley_ssmc::ContractBinding>),
    /// Kind 13, field 5 (`Contract.resource_limits`).
    ContractResourceLimits(Option<sley_ssmc::ResourceLimits>),
    /// Kind 14, field 1 (`TestCase.target`).
    TestCaseTarget(EntityId),
    /// Kind 14, field 2 (`TestCase.inputs`).
    TestCaseInputs(Vec<sley_ssmc::ConstValue>),
    /// Kind 14, field 3 (`TestCase.effect_environment`).
    TestCaseEffectEnvironment(sley_ssmc::EffectEnvironment),
    /// Kind 14, field 4 (`TestCase.expected`).
    TestCaseExpected(sley_ssmc::ExpectedOutcome),
    /// Kind 14, field 5 (`TestCase.observations`).
    TestCaseObservations(Vec<sley_ssmc::ExpectedObservation>),
    /// Kind 14, field 6 (`TestCase.resource_limits`).
    TestCaseResourceLimits(sley_ssmc::ResourceLimits),
    /// Kind 15, field 1 (`AdapterImport.adapter_id`).
    AdapterImportAdapterId([u8; 32]),
    /// Kind 15, field 2 (`AdapterImport.abi_version`).
    AdapterImportAbiVersion(u32),
    /// Kind 15, field 3 (`AdapterImport.request_type`).
    AdapterImportRequestType(sley_ssmc::TypeExpr),
    /// Kind 15, field 4 (`AdapterImport.response_type`).
    AdapterImportResponseType(sley_ssmc::TypeExpr),
    /// Kind 15, field 5 (`AdapterImport.failure_type`).
    AdapterImportFailureType(sley_ssmc::TypeExpr),
    /// Kind 15, field 6 (`AdapterImport.effects`).
    AdapterImportEffects(EntityIdSet),
    /// Kind 16, field 1 (`EntryPoint.function`).
    EntryPointFunction(EntityId),
    /// Kind 16, field 2 (`EntryPoint.exposure`).
    EntryPointExposure(EntryExposure),
    /// Kind 17, field 1 (`PolicyBinding.subject`).
    PolicyBindingSubject(EntityId),
    /// Kind 17, field 2 (`PolicyBinding.requirements`).
    PolicyBindingRequirements(EntityIdSet),
    /// Kind 18, field 1 (`DependencyBinding.dependency_root`).
    DependencyBindingDependencyRoot(StateRoot),
    /// Kind 18, field 2 (`DependencyBinding.external_package`).
    DependencyBindingExternalPackage(EntityId),
    /// Kind 18, field 3 (`DependencyBinding.local_namespace`).
    DependencyBindingLocalNamespace(EntityId),
}

impl FieldValue {
    /// Returns the exact closed field-value discriminant.
    #[must_use]
    pub const fn value_kind(&self) -> FieldValueKind {
        match self {
            Self::WorkspacePackages(..) => FieldValueKind::WorkspacePackages,
            Self::WorkspaceRootNamespace(..) => FieldValueKind::WorkspaceRootNamespace,
            Self::WorkspaceCapabilityRequirements(..) => FieldValueKind::WorkspaceCapabilityRequirements,
            Self::WorkspaceContracts(..) => FieldValueKind::WorkspaceContracts,
            Self::WorkspaceTests(..) => FieldValueKind::WorkspaceTests,
            Self::PackageWorkspace(..) => FieldValueKind::PackageWorkspace,
            Self::PackageRootNamespace(..) => FieldValueKind::PackageRootNamespace,
            Self::PackageDependencies(..) => FieldValueKind::PackageDependencies,
            Self::PackageExports(..) => FieldValueKind::PackageExports,
            Self::NamespaceParent(..) => FieldValueKind::NamespaceParent,
            Self::NamespaceMembers(..) => FieldValueKind::NamespaceMembers,
            Self::TypeDefTypeParameters(..) => FieldValueKind::TypeDefTypeParameters,
            Self::TypeDefForm(..) => FieldValueKind::TypeDefForm,
            Self::TypeDefInvariants(..) => FieldValueKind::TypeDefInvariants,
            Self::TypeDefVisibility(..) => FieldValueKind::TypeDefVisibility,
            Self::FunctionTypeParameters(..) => FieldValueKind::FunctionTypeParameters,
            Self::FunctionParameters(..) => FieldValueKind::FunctionParameters,
            Self::FunctionResultType(..) => FieldValueKind::FunctionResultType,
            Self::FunctionEffects(..) => FieldValueKind::FunctionEffects,
            Self::FunctionEntryBlock(..) => FieldValueKind::FunctionEntryBlock,
            Self::FunctionBlocks(..) => FieldValueKind::FunctionBlocks,
            Self::FunctionContracts(..) => FieldValueKind::FunctionContracts,
            Self::FunctionVisibility(..) => FieldValueKind::FunctionVisibility,
            Self::ParameterOwner(..) => FieldValueKind::ParameterOwner,
            Self::ParameterRole(..) => FieldValueKind::ParameterRole,
            Self::ParameterOrdinal(..) => FieldValueKind::ParameterOrdinal,
            Self::ParameterValueType(..) => FieldValueKind::ParameterValueType,
            Self::BlockFunction(..) => FieldValueKind::BlockFunction,
            Self::BlockParameters(..) => FieldValueKind::BlockParameters,
            Self::BlockOperations(..) => FieldValueKind::BlockOperations,
            Self::BlockTerminator(..) => FieldValueKind::BlockTerminator,
            Self::BlockReachability(..) => FieldValueKind::BlockReachability,
            Self::OperationBlock(..) => FieldValueKind::OperationBlock,
            Self::OperationOrdinal(..) => FieldValueKind::OperationOrdinal,
            Self::OperationOpcode(..) => FieldValueKind::OperationOpcode,
            Self::OperationOperands(..) => FieldValueKind::OperationOperands,
            Self::OperationResultTypes(..) => FieldValueKind::OperationResultTypes,
            Self::OperationImmediate(..) => FieldValueKind::OperationImmediate,
            Self::ConstantValue(..) => FieldValueKind::ConstantValue,
            Self::GlobalValueValueType(..) => FieldValueKind::GlobalValueValueType,
            Self::GlobalValueInitializer(..) => FieldValueKind::GlobalValueInitializer,
            Self::GlobalValueVisibility(..) => FieldValueKind::GlobalValueVisibility,
            Self::EffectDefEffectKind(..) => FieldValueKind::EffectDefEffectKind,
            Self::EffectDefScopeType(..) => FieldValueKind::EffectDefScopeType,
            Self::EffectDefRequestType(..) => FieldValueKind::EffectDefRequestType,
            Self::EffectDefResponseType(..) => FieldValueKind::EffectDefResponseType,
            Self::EffectDefFailureType(..) => FieldValueKind::EffectDefFailureType,
            Self::EffectDefVisibility(..) => FieldValueKind::EffectDefVisibility,
            Self::CapabilityRequirementEffect(..) => FieldValueKind::CapabilityRequirementEffect,
            Self::CapabilityRequirementAllowedScopes(..) => FieldValueKind::CapabilityRequirementAllowedScopes,
            Self::CapabilityRequirementConstraintContracts(..) => FieldValueKind::CapabilityRequirementConstraintContracts,
            Self::ContractTarget(..) => FieldValueKind::ContractTarget,
            Self::ContractContractKind(..) => FieldValueKind::ContractContractKind,
            Self::ContractPredicate(..) => FieldValueKind::ContractPredicate,
            Self::ContractBindings(..) => FieldValueKind::ContractBindings,
            Self::ContractResourceLimits(..) => FieldValueKind::ContractResourceLimits,
            Self::TestCaseTarget(..) => FieldValueKind::TestCaseTarget,
            Self::TestCaseInputs(..) => FieldValueKind::TestCaseInputs,
            Self::TestCaseEffectEnvironment(..) => FieldValueKind::TestCaseEffectEnvironment,
            Self::TestCaseExpected(..) => FieldValueKind::TestCaseExpected,
            Self::TestCaseObservations(..) => FieldValueKind::TestCaseObservations,
            Self::TestCaseResourceLimits(..) => FieldValueKind::TestCaseResourceLimits,
            Self::AdapterImportAdapterId(..) => FieldValueKind::AdapterImportAdapterId,
            Self::AdapterImportAbiVersion(..) => FieldValueKind::AdapterImportAbiVersion,
            Self::AdapterImportRequestType(..) => FieldValueKind::AdapterImportRequestType,
            Self::AdapterImportResponseType(..) => FieldValueKind::AdapterImportResponseType,
            Self::AdapterImportFailureType(..) => FieldValueKind::AdapterImportFailureType,
            Self::AdapterImportEffects(..) => FieldValueKind::AdapterImportEffects,
            Self::EntryPointFunction(..) => FieldValueKind::EntryPointFunction,
            Self::EntryPointExposure(..) => FieldValueKind::EntryPointExposure,
            Self::PolicyBindingSubject(..) => FieldValueKind::PolicyBindingSubject,
            Self::PolicyBindingRequirements(..) => FieldValueKind::PolicyBindingRequirements,
            Self::DependencyBindingDependencyRoot(..) => FieldValueKind::DependencyBindingDependencyRoot,
            Self::DependencyBindingExternalPackage(..) => FieldValueKind::DependencyBindingExternalPackage,
            Self::DependencyBindingLocalNamespace(..) => FieldValueKind::DependencyBindingLocalNamespace,
        }
    }

    /// Returns the exact `(entity_kind, field_tag)` selected by this value.
    #[must_use]
    pub const fn field_key(&self) -> (u16, u16) {
        self.value_kind().field_key()
    }
}

/// Closed descriptor-selectable proposal-value discriminant.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum ProposalValueKind {
    /// Unit operation payload with no body bytes.
    Unit,
    /// One complete entity-body kind.
    EntityBody(EntityBodyValueKind),
    /// One exact body-field kind.
    Field(FieldValueKind),
}

/// Closed proposal value before any candidate record exists.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ProposalValue {
    /// Unit operation payload with no body bytes.
    Unit,
    /// One complete entity body.
    EntityBody(EntityBodyValue),
    /// One exact entity-body field.
    Field(FieldValue),
}

impl ProposalValue {
    /// Returns the exact closed discriminant used for descriptor admission.
    #[must_use]
    pub const fn value_kind(&self) -> ProposalValueKind {
        match self {
            Self::Unit => ProposalValueKind::Unit,
            Self::EntityBody(value) => ProposalValueKind::EntityBody(value.value_kind()),
            Self::Field(value) => ProposalValueKind::Field(value.value_kind()),
        }
    }
}

/// One exact immutable mutation descriptor to closed value-kind binding.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct TypedValueBinding {
    /// Closed mutation class.
    pub class: MutationClass,
    /// Exact target entity kind.
    pub target_kind: u16,
    /// Exact field tag, or `None` for a complete body or Unit operation.
    pub field_tag: Option<u16>,
    /// Exact closed proposal-value kind.
    pub value_kind: ProposalValueKind,
}

/// Complete immutable descriptor-to-value-kind binding table.
pub const TYPED_VALUE_BINDINGS: &[TypedValueBinding] = &[
    TypedValueBinding {
        class: MutationClass::CreateEntity,
        target_kind: 1,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::Workspace),
    },
    TypedValueBinding {
        class: MutationClass::CreateEntity,
        target_kind: 2,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::Package),
    },
    TypedValueBinding {
        class: MutationClass::CreateEntity,
        target_kind: 3,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::Namespace),
    },
    TypedValueBinding {
        class: MutationClass::CreateEntity,
        target_kind: 4,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::TypeDef),
    },
    TypedValueBinding {
        class: MutationClass::CreateEntity,
        target_kind: 5,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::Function),
    },
    TypedValueBinding {
        class: MutationClass::CreateEntity,
        target_kind: 6,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::Parameter),
    },
    TypedValueBinding {
        class: MutationClass::CreateEntity,
        target_kind: 7,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::Block),
    },
    TypedValueBinding {
        class: MutationClass::CreateEntity,
        target_kind: 8,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::Operation),
    },
    TypedValueBinding {
        class: MutationClass::CreateEntity,
        target_kind: 9,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::Constant),
    },
    TypedValueBinding {
        class: MutationClass::CreateEntity,
        target_kind: 10,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::GlobalValue),
    },
    TypedValueBinding {
        class: MutationClass::CreateEntity,
        target_kind: 11,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::EffectDef),
    },
    TypedValueBinding {
        class: MutationClass::CreateEntity,
        target_kind: 12,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::CapabilityRequirement),
    },
    TypedValueBinding {
        class: MutationClass::CreateEntity,
        target_kind: 13,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::Contract),
    },
    TypedValueBinding {
        class: MutationClass::CreateEntity,
        target_kind: 14,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::TestCase),
    },
    TypedValueBinding {
        class: MutationClass::CreateEntity,
        target_kind: 15,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::AdapterImport),
    },
    TypedValueBinding {
        class: MutationClass::CreateEntity,
        target_kind: 16,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::EntryPoint),
    },
    TypedValueBinding {
        class: MutationClass::CreateEntity,
        target_kind: 17,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::PolicyBinding),
    },
    TypedValueBinding {
        class: MutationClass::CreateEntity,
        target_kind: 18,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::DependencyBinding),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceEntityVersion,
        target_kind: 1,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::Workspace),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceEntityVersion,
        target_kind: 2,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::Package),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceEntityVersion,
        target_kind: 3,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::Namespace),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceEntityVersion,
        target_kind: 4,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::TypeDef),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceEntityVersion,
        target_kind: 5,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::Function),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceEntityVersion,
        target_kind: 6,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::Parameter),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceEntityVersion,
        target_kind: 7,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::Block),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceEntityVersion,
        target_kind: 8,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::Operation),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceEntityVersion,
        target_kind: 9,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::Constant),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceEntityVersion,
        target_kind: 10,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::GlobalValue),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceEntityVersion,
        target_kind: 11,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::EffectDef),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceEntityVersion,
        target_kind: 12,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::CapabilityRequirement),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceEntityVersion,
        target_kind: 13,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::Contract),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceEntityVersion,
        target_kind: 14,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::TestCase),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceEntityVersion,
        target_kind: 15,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::AdapterImport),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceEntityVersion,
        target_kind: 16,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::EntryPoint),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceEntityVersion,
        target_kind: 17,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::PolicyBinding),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceEntityVersion,
        target_kind: 18,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::DependencyBinding),
    },
    TypedValueBinding {
        class: MutationClass::DeleteEntityBinding,
        target_kind: 1,
        field_tag: None,
        value_kind: ProposalValueKind::Unit,
    },
    TypedValueBinding {
        class: MutationClass::DeleteEntityBinding,
        target_kind: 2,
        field_tag: None,
        value_kind: ProposalValueKind::Unit,
    },
    TypedValueBinding {
        class: MutationClass::DeleteEntityBinding,
        target_kind: 3,
        field_tag: None,
        value_kind: ProposalValueKind::Unit,
    },
    TypedValueBinding {
        class: MutationClass::DeleteEntityBinding,
        target_kind: 4,
        field_tag: None,
        value_kind: ProposalValueKind::Unit,
    },
    TypedValueBinding {
        class: MutationClass::DeleteEntityBinding,
        target_kind: 5,
        field_tag: None,
        value_kind: ProposalValueKind::Unit,
    },
    TypedValueBinding {
        class: MutationClass::DeleteEntityBinding,
        target_kind: 6,
        field_tag: None,
        value_kind: ProposalValueKind::Unit,
    },
    TypedValueBinding {
        class: MutationClass::DeleteEntityBinding,
        target_kind: 7,
        field_tag: None,
        value_kind: ProposalValueKind::Unit,
    },
    TypedValueBinding {
        class: MutationClass::DeleteEntityBinding,
        target_kind: 8,
        field_tag: None,
        value_kind: ProposalValueKind::Unit,
    },
    TypedValueBinding {
        class: MutationClass::DeleteEntityBinding,
        target_kind: 9,
        field_tag: None,
        value_kind: ProposalValueKind::Unit,
    },
    TypedValueBinding {
        class: MutationClass::DeleteEntityBinding,
        target_kind: 10,
        field_tag: None,
        value_kind: ProposalValueKind::Unit,
    },
    TypedValueBinding {
        class: MutationClass::DeleteEntityBinding,
        target_kind: 11,
        field_tag: None,
        value_kind: ProposalValueKind::Unit,
    },
    TypedValueBinding {
        class: MutationClass::DeleteEntityBinding,
        target_kind: 12,
        field_tag: None,
        value_kind: ProposalValueKind::Unit,
    },
    TypedValueBinding {
        class: MutationClass::DeleteEntityBinding,
        target_kind: 13,
        field_tag: None,
        value_kind: ProposalValueKind::Unit,
    },
    TypedValueBinding {
        class: MutationClass::DeleteEntityBinding,
        target_kind: 14,
        field_tag: None,
        value_kind: ProposalValueKind::Unit,
    },
    TypedValueBinding {
        class: MutationClass::DeleteEntityBinding,
        target_kind: 15,
        field_tag: None,
        value_kind: ProposalValueKind::Unit,
    },
    TypedValueBinding {
        class: MutationClass::DeleteEntityBinding,
        target_kind: 16,
        field_tag: None,
        value_kind: ProposalValueKind::Unit,
    },
    TypedValueBinding {
        class: MutationClass::DeleteEntityBinding,
        target_kind: 17,
        field_tag: None,
        value_kind: ProposalValueKind::Unit,
    },
    TypedValueBinding {
        class: MutationClass::DeleteEntityBinding,
        target_kind: 18,
        field_tag: None,
        value_kind: ProposalValueKind::Unit,
    },
    TypedValueBinding {
        class: MutationClass::SetScalarField,
        target_kind: 4,
        field_tag: Some(4),
        value_kind: ProposalValueKind::Field(FieldValueKind::TypeDefVisibility),
    },
    TypedValueBinding {
        class: MutationClass::SetScalarField,
        target_kind: 5,
        field_tag: Some(8),
        value_kind: ProposalValueKind::Field(FieldValueKind::FunctionVisibility),
    },
    TypedValueBinding {
        class: MutationClass::SetScalarField,
        target_kind: 6,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::ParameterRole),
    },
    TypedValueBinding {
        class: MutationClass::SetScalarField,
        target_kind: 6,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::ParameterOrdinal),
    },
    TypedValueBinding {
        class: MutationClass::SetScalarField,
        target_kind: 7,
        field_tag: Some(5),
        value_kind: ProposalValueKind::Field(FieldValueKind::BlockReachability),
    },
    TypedValueBinding {
        class: MutationClass::SetScalarField,
        target_kind: 8,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::OperationOrdinal),
    },
    TypedValueBinding {
        class: MutationClass::SetScalarField,
        target_kind: 8,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::OperationOpcode),
    },
    TypedValueBinding {
        class: MutationClass::SetScalarField,
        target_kind: 10,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::GlobalValueVisibility),
    },
    TypedValueBinding {
        class: MutationClass::SetScalarField,
        target_kind: 11,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::EffectDefEffectKind),
    },
    TypedValueBinding {
        class: MutationClass::SetScalarField,
        target_kind: 11,
        field_tag: Some(6),
        value_kind: ProposalValueKind::Field(FieldValueKind::EffectDefVisibility),
    },
    TypedValueBinding {
        class: MutationClass::SetScalarField,
        target_kind: 13,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::ContractContractKind),
    },
    TypedValueBinding {
        class: MutationClass::SetScalarField,
        target_kind: 15,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::AdapterImportAdapterId),
    },
    TypedValueBinding {
        class: MutationClass::SetScalarField,
        target_kind: 15,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::AdapterImportAbiVersion),
    },
    TypedValueBinding {
        class: MutationClass::SetScalarField,
        target_kind: 16,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::EntryPointExposure),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 1,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::WorkspacePackages),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 1,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::WorkspaceRootNamespace),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 1,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::WorkspaceCapabilityRequirements),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 1,
        field_tag: Some(4),
        value_kind: ProposalValueKind::Field(FieldValueKind::WorkspaceContracts),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 1,
        field_tag: Some(5),
        value_kind: ProposalValueKind::Field(FieldValueKind::WorkspaceTests),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 2,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::PackageWorkspace),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 2,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::PackageRootNamespace),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 2,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::PackageDependencies),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 2,
        field_tag: Some(4),
        value_kind: ProposalValueKind::Field(FieldValueKind::PackageExports),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 3,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::NamespaceParent),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 3,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::NamespaceMembers),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 4,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::TypeDefTypeParameters),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 4,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::TypeDefForm),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 4,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::TypeDefInvariants),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 4,
        field_tag: Some(4),
        value_kind: ProposalValueKind::Field(FieldValueKind::TypeDefVisibility),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 5,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::FunctionTypeParameters),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 5,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::FunctionParameters),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 5,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::FunctionResultType),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 5,
        field_tag: Some(4),
        value_kind: ProposalValueKind::Field(FieldValueKind::FunctionEffects),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 5,
        field_tag: Some(5),
        value_kind: ProposalValueKind::Field(FieldValueKind::FunctionEntryBlock),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 5,
        field_tag: Some(6),
        value_kind: ProposalValueKind::Field(FieldValueKind::FunctionBlocks),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 5,
        field_tag: Some(7),
        value_kind: ProposalValueKind::Field(FieldValueKind::FunctionContracts),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 5,
        field_tag: Some(8),
        value_kind: ProposalValueKind::Field(FieldValueKind::FunctionVisibility),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 6,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::ParameterOwner),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 6,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::ParameterRole),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 6,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::ParameterOrdinal),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 6,
        field_tag: Some(4),
        value_kind: ProposalValueKind::Field(FieldValueKind::ParameterValueType),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 7,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::BlockFunction),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 7,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::BlockParameters),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 7,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::BlockOperations),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 7,
        field_tag: Some(4),
        value_kind: ProposalValueKind::Field(FieldValueKind::BlockTerminator),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 7,
        field_tag: Some(5),
        value_kind: ProposalValueKind::Field(FieldValueKind::BlockReachability),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 8,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::OperationBlock),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 8,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::OperationOrdinal),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 8,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::OperationOpcode),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 8,
        field_tag: Some(4),
        value_kind: ProposalValueKind::Field(FieldValueKind::OperationOperands),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 8,
        field_tag: Some(5),
        value_kind: ProposalValueKind::Field(FieldValueKind::OperationResultTypes),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 8,
        field_tag: Some(6),
        value_kind: ProposalValueKind::Field(FieldValueKind::OperationImmediate),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 9,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::ConstantValue),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 10,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::GlobalValueValueType),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 10,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::GlobalValueInitializer),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 10,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::GlobalValueVisibility),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 11,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::EffectDefEffectKind),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 11,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::EffectDefScopeType),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 11,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::EffectDefRequestType),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 11,
        field_tag: Some(4),
        value_kind: ProposalValueKind::Field(FieldValueKind::EffectDefResponseType),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 11,
        field_tag: Some(5),
        value_kind: ProposalValueKind::Field(FieldValueKind::EffectDefFailureType),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 11,
        field_tag: Some(6),
        value_kind: ProposalValueKind::Field(FieldValueKind::EffectDefVisibility),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 12,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::CapabilityRequirementEffect),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 12,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::CapabilityRequirementAllowedScopes),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 12,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::CapabilityRequirementConstraintContracts),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 13,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::ContractTarget),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 13,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::ContractContractKind),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 13,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::ContractPredicate),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 13,
        field_tag: Some(4),
        value_kind: ProposalValueKind::Field(FieldValueKind::ContractBindings),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 13,
        field_tag: Some(5),
        value_kind: ProposalValueKind::Field(FieldValueKind::ContractResourceLimits),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 14,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::TestCaseTarget),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 14,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::TestCaseInputs),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 14,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::TestCaseEffectEnvironment),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 14,
        field_tag: Some(4),
        value_kind: ProposalValueKind::Field(FieldValueKind::TestCaseExpected),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 14,
        field_tag: Some(5),
        value_kind: ProposalValueKind::Field(FieldValueKind::TestCaseObservations),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 14,
        field_tag: Some(6),
        value_kind: ProposalValueKind::Field(FieldValueKind::TestCaseResourceLimits),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 15,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::AdapterImportAdapterId),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 15,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::AdapterImportAbiVersion),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 15,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::AdapterImportRequestType),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 15,
        field_tag: Some(4),
        value_kind: ProposalValueKind::Field(FieldValueKind::AdapterImportResponseType),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 15,
        field_tag: Some(5),
        value_kind: ProposalValueKind::Field(FieldValueKind::AdapterImportFailureType),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 15,
        field_tag: Some(6),
        value_kind: ProposalValueKind::Field(FieldValueKind::AdapterImportEffects),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 16,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::EntryPointFunction),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 16,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::EntryPointExposure),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 17,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::PolicyBindingSubject),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 17,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::PolicyBindingRequirements),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 18,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::DependencyBindingDependencyRoot),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 18,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::DependencyBindingExternalPackage),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTypedField,
        target_kind: 18,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::DependencyBindingLocalNamespace),
    },
    TypedValueBinding {
        class: MutationClass::RetargetReference,
        target_kind: 1,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::WorkspaceRootNamespace),
    },
    TypedValueBinding {
        class: MutationClass::RetargetReference,
        target_kind: 2,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::PackageWorkspace),
    },
    TypedValueBinding {
        class: MutationClass::RetargetReference,
        target_kind: 2,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::PackageRootNamespace),
    },
    TypedValueBinding {
        class: MutationClass::RetargetReference,
        target_kind: 3,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::NamespaceParent),
    },
    TypedValueBinding {
        class: MutationClass::RetargetReference,
        target_kind: 5,
        field_tag: Some(5),
        value_kind: ProposalValueKind::Field(FieldValueKind::FunctionEntryBlock),
    },
    TypedValueBinding {
        class: MutationClass::RetargetReference,
        target_kind: 6,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::ParameterOwner),
    },
    TypedValueBinding {
        class: MutationClass::RetargetReference,
        target_kind: 7,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::BlockFunction),
    },
    TypedValueBinding {
        class: MutationClass::RetargetReference,
        target_kind: 8,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::OperationBlock),
    },
    TypedValueBinding {
        class: MutationClass::RetargetReference,
        target_kind: 10,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::GlobalValueInitializer),
    },
    TypedValueBinding {
        class: MutationClass::RetargetReference,
        target_kind: 12,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::CapabilityRequirementEffect),
    },
    TypedValueBinding {
        class: MutationClass::RetargetReference,
        target_kind: 13,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::ContractTarget),
    },
    TypedValueBinding {
        class: MutationClass::RetargetReference,
        target_kind: 13,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::ContractPredicate),
    },
    TypedValueBinding {
        class: MutationClass::RetargetReference,
        target_kind: 14,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::TestCaseTarget),
    },
    TypedValueBinding {
        class: MutationClass::RetargetReference,
        target_kind: 16,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::EntryPointFunction),
    },
    TypedValueBinding {
        class: MutationClass::RetargetReference,
        target_kind: 17,
        field_tag: Some(1),
        value_kind: ProposalValueKind::Field(FieldValueKind::PolicyBindingSubject),
    },
    TypedValueBinding {
        class: MutationClass::RetargetReference,
        target_kind: 18,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::DependencyBindingExternalPackage),
    },
    TypedValueBinding {
        class: MutationClass::RetargetReference,
        target_kind: 18,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::DependencyBindingLocalNamespace),
    },
    TypedValueBinding {
        class: MutationClass::InsertOrderedChild,
        target_kind: 5,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::FunctionParameters),
    },
    TypedValueBinding {
        class: MutationClass::InsertOrderedChild,
        target_kind: 5,
        field_tag: Some(6),
        value_kind: ProposalValueKind::Field(FieldValueKind::FunctionBlocks),
    },
    TypedValueBinding {
        class: MutationClass::InsertOrderedChild,
        target_kind: 7,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::BlockParameters),
    },
    TypedValueBinding {
        class: MutationClass::InsertOrderedChild,
        target_kind: 7,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::BlockOperations),
    },
    TypedValueBinding {
        class: MutationClass::RemoveOrderedChild,
        target_kind: 5,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::FunctionParameters),
    },
    TypedValueBinding {
        class: MutationClass::RemoveOrderedChild,
        target_kind: 5,
        field_tag: Some(6),
        value_kind: ProposalValueKind::Field(FieldValueKind::FunctionBlocks),
    },
    TypedValueBinding {
        class: MutationClass::RemoveOrderedChild,
        target_kind: 7,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::BlockParameters),
    },
    TypedValueBinding {
        class: MutationClass::RemoveOrderedChild,
        target_kind: 7,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::BlockOperations),
    },
    TypedValueBinding {
        class: MutationClass::MoveOrderedChild,
        target_kind: 5,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::FunctionParameters),
    },
    TypedValueBinding {
        class: MutationClass::MoveOrderedChild,
        target_kind: 5,
        field_tag: Some(6),
        value_kind: ProposalValueKind::Field(FieldValueKind::FunctionBlocks),
    },
    TypedValueBinding {
        class: MutationClass::MoveOrderedChild,
        target_kind: 7,
        field_tag: Some(2),
        value_kind: ProposalValueKind::Field(FieldValueKind::BlockParameters),
    },
    TypedValueBinding {
        class: MutationClass::MoveOrderedChild,
        target_kind: 7,
        field_tag: Some(3),
        value_kind: ProposalValueKind::Field(FieldValueKind::BlockOperations),
    },
    TypedValueBinding {
        class: MutationClass::AddEntryPoint,
        target_kind: 16,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::EntryPoint),
    },
    TypedValueBinding {
        class: MutationClass::RemoveEntryPoint,
        target_kind: 16,
        field_tag: None,
        value_kind: ProposalValueKind::Unit,
    },
    TypedValueBinding {
        class: MutationClass::AddTest,
        target_kind: 14,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::TestCase),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceTest,
        target_kind: 14,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::TestCase),
    },
    TypedValueBinding {
        class: MutationClass::AddContract,
        target_kind: 13,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::Contract),
    },
    TypedValueBinding {
        class: MutationClass::ReplaceContract,
        target_kind: 13,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::Contract),
    },
    TypedValueBinding {
        class: MutationClass::UpdateDependencyBinding,
        target_kind: 18,
        field_tag: None,
        value_kind: ProposalValueKind::EntityBody(EntityBodyValueKind::DependencyBinding),
    },
];
