// @generated by scripts/generate_mutation_value_codecs.py; DO NOT EDIT.
// source: docs/spec/SSMC1_EPOCH1_SCHEMA.txt; blake3-256: 044d21d328e40d517fd09fd099c9697fbba2c95d0a519eade333c1140d648e73

/// BLAKE3-256 of the exact canonical schema manifest used for host values.
pub const VALUE_HOST_SOURCE_SCHEMA_BLAKE3: [u8; 32] = [0x04, 0x4d, 0x21, 0xd3, 0x28, 0xe4, 0x0d, 0x51, 0x7f, 0xd0, 0x9f, 0xd0, 0x99, 0xc9, 0x69, 0x7f, 0xbb, 0xa2, 0xc9, 0x5d, 0x0a, 0x51, 0x9e, 0xad, 0xe3, 0x33, 0xc1, 0x14, 0x0d, 0x64, 0x8e, 0x73];
/// Closed entity-body host-value count.
pub const ENTITY_BODY_VALUE_COUNT: usize = 18;
/// Closed entity-body field-value count.
pub const FIELD_VALUE_COUNT: usize = 75;

/// Closed proposal-only body for entity kind 1 (`Workspace`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WorkspaceBody {
    /// Exact manifest field 1 (`packages`).
    pub packages: EntityIdSet,
    /// Exact manifest field 2 (`root_namespace`).
    pub root_namespace: EntityId,
    /// Exact manifest field 3 (`capability_requirements`).
    pub capability_requirements: EntityIdSet,
    /// Exact manifest field 4 (`contracts`).
    pub contracts: EntityIdSet,
    /// Exact manifest field 5 (`tests`).
    pub tests: EntityIdSet,
}

/// Closed proposal-only body for entity kind 2 (`Package`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PackageBody {
    /// Exact manifest field 1 (`workspace`).
    pub workspace: EntityId,
    /// Exact manifest field 2 (`root_namespace`).
    pub root_namespace: EntityId,
    /// Exact manifest field 3 (`dependencies`).
    pub dependencies: EntityIdSet,
    /// Exact manifest field 4 (`exports`).
    pub exports: EntityIdSet,
}

/// Closed proposal-only body for entity kind 3 (`Namespace`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NamespaceBody {
    /// Exact manifest field 1 (`parent`).
    pub parent: Option<EntityId>,
    /// Exact manifest field 2 (`members`).
    pub members: EntityIdSet,
}

/// Closed proposal-only body for entity kind 4 (`TypeDef`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TypeDefBody {
    /// Exact manifest field 1 (`type_parameters`).
    pub type_parameters: Vec<sley_ssmc::TypeParameterDef>,
    /// Exact manifest field 2 (`form`).
    pub form: sley_ssmc::TypeDefForm,
    /// Exact manifest field 3 (`invariants`).
    pub invariants: EntityIdSet,
    /// Exact manifest field 4 (`visibility`).
    pub visibility: sley_ssmc::Visibility,
}

/// Closed proposal-only body for entity kind 5 (`Function`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct FunctionBody {
    /// Exact manifest field 1 (`type_parameters`).
    pub type_parameters: Vec<sley_ssmc::TypeParameterDef>,
    /// Exact manifest field 2 (`parameters`).
    pub parameters: Vec<EntityId>,
    /// Exact manifest field 3 (`result_type`).
    pub result_type: sley_ssmc::TypeExpr,
    /// Exact manifest field 4 (`effects`).
    pub effects: EntityIdSet,
    /// Exact manifest field 5 (`entry_block`).
    pub entry_block: EntityId,
    /// Exact manifest field 6 (`blocks`).
    pub blocks: Vec<EntityId>,
    /// Exact manifest field 7 (`contracts`).
    pub contracts: EntityIdSet,
    /// Exact manifest field 8 (`visibility`).
    pub visibility: sley_ssmc::Visibility,
}

/// Closed proposal-only body for entity kind 6 (`Parameter`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ParameterBody {
    /// Exact manifest field 1 (`owner`).
    pub owner: EntityId,
    /// Exact manifest field 2 (`role`).
    pub role: sley_ssmc::ParameterRole,
    /// Exact manifest field 3 (`ordinal`).
    pub ordinal: u32,
    /// Exact manifest field 4 (`value_type`).
    pub value_type: sley_ssmc::TypeExpr,
}

/// Closed proposal-only body for entity kind 7 (`Block`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct BlockBody {
    /// Exact manifest field 1 (`function`).
    pub function: EntityId,
    /// Exact manifest field 2 (`parameters`).
    pub parameters: Vec<EntityId>,
    /// Exact manifest field 3 (`operations`).
    pub operations: Vec<EntityId>,
    /// Exact manifest field 4 (`terminator`).
    pub terminator: sley_ssmc::Terminator,
    /// Exact manifest field 5 (`reachability`).
    pub reachability: sley_ssmc::Reachability,
}

/// Closed proposal-only body for entity kind 8 (`Operation`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OperationBody {
    /// Exact manifest field 1 (`block`).
    pub block: EntityId,
    /// Exact manifest field 2 (`ordinal`).
    pub ordinal: u32,
    /// Exact manifest field 3 (`opcode`).
    pub opcode: u32,
    /// Exact manifest field 4 (`operands`).
    pub operands: Vec<sley_ssmc::ValueRef>,
    /// Exact manifest field 5 (`result_types`).
    pub result_types: Vec<sley_ssmc::TypeExpr>,
    /// Exact manifest field 6 (`immediate`).
    pub immediate: sley_ssmc::Immediate,
}

/// Closed proposal-only body for entity kind 9 (`Constant`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ConstantBody {
    /// Exact manifest field 1 (`value`).
    pub value: sley_ssmc::ConstValue,
}

/// Closed proposal-only body for entity kind 10 (`GlobalValue`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GlobalValueBody {
    /// Exact manifest field 1 (`value_type`).
    pub value_type: sley_ssmc::TypeExpr,
    /// Exact manifest field 2 (`initializer`).
    pub initializer: EntityId,
    /// Exact manifest field 3 (`visibility`).
    pub visibility: sley_ssmc::Visibility,
}

/// Closed proposal-only body for entity kind 11 (`EffectDef`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EffectDefBody {
    /// Exact manifest field 1 (`effect_kind`).
    pub effect_kind: sley_ssmc::EffectKind,
    /// Exact manifest field 2 (`scope_type`).
    pub scope_type: sley_ssmc::TypeExpr,
    /// Exact manifest field 3 (`request_type`).
    pub request_type: sley_ssmc::TypeExpr,
    /// Exact manifest field 4 (`response_type`).
    pub response_type: sley_ssmc::TypeExpr,
    /// Exact manifest field 5 (`failure_type`).
    pub failure_type: sley_ssmc::TypeExpr,
    /// Exact manifest field 6 (`visibility`).
    pub visibility: sley_ssmc::Visibility,
}

/// Closed proposal-only body for entity kind 12 (`CapabilityRequirement`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CapabilityRequirementBody {
    /// Exact manifest field 1 (`effect`).
    pub effect: EntityId,
    /// Exact manifest field 2 (`allowed_scopes`).
    pub allowed_scopes: Vec<sley_ssmc::ConstValue>,
    /// Exact manifest field 3 (`constraint_contracts`).
    pub constraint_contracts: EntityIdSet,
}

/// Closed proposal-only body for entity kind 13 (`Contract`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ContractBody {
    /// Exact manifest field 1 (`target`).
    pub target: EntityId,
    /// Exact manifest field 2 (`contract_kind`).
    pub contract_kind: sley_ssmc::ContractKind,
    /// Exact manifest field 3 (`predicate`).
    pub predicate: EntityId,
    /// Exact manifest field 4 (`bindings`).
    pub bindings: Vec<sley_ssmc::ContractBinding>,
    /// Exact manifest field 5 (`resource_limits`).
    pub resource_limits: Option<sley_ssmc::ResourceLimits>,
}

/// Closed proposal-only body for entity kind 14 (`TestCase`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TestCaseBody {
    /// Exact manifest field 1 (`target`).
    pub target: EntityId,
    /// Exact manifest field 2 (`inputs`).
    pub inputs: Vec<sley_ssmc::ConstValue>,
    /// Exact manifest field 3 (`effect_environment`).
    pub effect_environment: sley_ssmc::EffectEnvironment,
    /// Exact manifest field 4 (`expected`).
    pub expected: sley_ssmc::ExpectedOutcome,
    /// Exact manifest field 5 (`observations`).
    pub observations: Vec<sley_ssmc::ExpectedObservation>,
    /// Exact manifest field 6 (`resource_limits`).
    pub resource_limits: sley_ssmc::ResourceLimits,
}

/// Closed proposal-only body for entity kind 15 (`AdapterImport`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AdapterImportBody {
    /// Exact manifest field 1 (`adapter_id`).
    pub adapter_id: [u8; 32],
    /// Exact manifest field 2 (`abi_version`).
    pub abi_version: u32,
    /// Exact manifest field 3 (`request_type`).
    pub request_type: sley_ssmc::TypeExpr,
    /// Exact manifest field 4 (`response_type`).
    pub response_type: sley_ssmc::TypeExpr,
    /// Exact manifest field 5 (`failure_type`).
    pub failure_type: sley_ssmc::TypeExpr,
    /// Exact manifest field 6 (`effects`).
    pub effects: EntityIdSet,
}

/// Closed proposal-only body for entity kind 16 (`EntryPoint`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EntryPointBody {
    /// Exact manifest field 1 (`function`).
    pub function: EntityId,
    /// Exact manifest field 2 (`exposure`).
    pub exposure: EntryExposure,
}

/// Closed proposal-only body for entity kind 17 (`PolicyBinding`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PolicyBindingBody {
    /// Exact manifest field 1 (`subject`).
    pub subject: EntityId,
    /// Exact manifest field 2 (`requirements`).
    pub requirements: EntityIdSet,
}

/// Closed proposal-only body for entity kind 18 (`DependencyBinding`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DependencyBindingBody {
    /// Exact manifest field 1 (`dependency_root`).
    pub dependency_root: StateRoot,
    /// Exact manifest field 2 (`external_package`).
    pub external_package: EntityId,
    /// Exact manifest field 3 (`local_namespace`).
    pub local_namespace: EntityId,
}

/// Closed typed value for one complete SSMC1 entity body.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum EntityBodyValue {
    /// Entity kind 1 (`Workspace`).
    Workspace(WorkspaceBody),
    /// Entity kind 2 (`Package`).
    Package(PackageBody),
    /// Entity kind 3 (`Namespace`).
    Namespace(NamespaceBody),
    /// Entity kind 4 (`TypeDef`).
    TypeDef(TypeDefBody),
    /// Entity kind 5 (`Function`).
    Function(FunctionBody),
    /// Entity kind 6 (`Parameter`).
    Parameter(ParameterBody),
    /// Entity kind 7 (`Block`).
    Block(BlockBody),
    /// Entity kind 8 (`Operation`).
    Operation(OperationBody),
    /// Entity kind 9 (`Constant`).
    Constant(ConstantBody),
    /// Entity kind 10 (`GlobalValue`).
    GlobalValue(GlobalValueBody),
    /// Entity kind 11 (`EffectDef`).
    EffectDef(EffectDefBody),
    /// Entity kind 12 (`CapabilityRequirement`).
    CapabilityRequirement(CapabilityRequirementBody),
    /// Entity kind 13 (`Contract`).
    Contract(ContractBody),
    /// Entity kind 14 (`TestCase`).
    TestCase(TestCaseBody),
    /// Entity kind 15 (`AdapterImport`).
    AdapterImport(AdapterImportBody),
    /// Entity kind 16 (`EntryPoint`).
    EntryPoint(EntryPointBody),
    /// Entity kind 17 (`PolicyBinding`).
    PolicyBinding(PolicyBindingBody),
    /// Entity kind 18 (`DependencyBinding`).
    DependencyBinding(DependencyBindingBody),
}

impl EntityBodyValue {
    /// Returns the exact closed SSMC1 entity-kind tag.
    #[must_use]
    pub const fn kind_tag(&self) -> u16 {
        match self {
            Self::Workspace(..) => 1,
            Self::Package(..) => 2,
            Self::Namespace(..) => 3,
            Self::TypeDef(..) => 4,
            Self::Function(..) => 5,
            Self::Parameter(..) => 6,
            Self::Block(..) => 7,
            Self::Operation(..) => 8,
            Self::Constant(..) => 9,
            Self::GlobalValue(..) => 10,
            Self::EffectDef(..) => 11,
            Self::CapabilityRequirement(..) => 12,
            Self::Contract(..) => 13,
            Self::TestCase(..) => 14,
            Self::AdapterImport(..) => 15,
            Self::EntryPoint(..) => 16,
            Self::PolicyBinding(..) => 17,
            Self::DependencyBinding(..) => 18,
        }
    }
}

/// Closed typed value for one exact SSMC1 entity-body field.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum FieldValue {
    /// Kind 1, field 1 (`Workspace.packages`).
    WorkspacePackages(EntityIdSet),
    /// Kind 1, field 2 (`Workspace.root_namespace`).
    WorkspaceRootNamespace(EntityId),
    /// Kind 1, field 3 (`Workspace.capability_requirements`).
    WorkspaceCapabilityRequirements(EntityIdSet),
    /// Kind 1, field 4 (`Workspace.contracts`).
    WorkspaceContracts(EntityIdSet),
    /// Kind 1, field 5 (`Workspace.tests`).
    WorkspaceTests(EntityIdSet),
    /// Kind 2, field 1 (`Package.workspace`).
    PackageWorkspace(EntityId),
    /// Kind 2, field 2 (`Package.root_namespace`).
    PackageRootNamespace(EntityId),
    /// Kind 2, field 3 (`Package.dependencies`).
    PackageDependencies(EntityIdSet),
    /// Kind 2, field 4 (`Package.exports`).
    PackageExports(EntityIdSet),
    /// Kind 3, field 1 (`Namespace.parent`).
    NamespaceParent(Option<EntityId>),
    /// Kind 3, field 2 (`Namespace.members`).
    NamespaceMembers(EntityIdSet),
    /// Kind 4, field 1 (`TypeDef.type_parameters`).
    TypeDefTypeParameters(Vec<sley_ssmc::TypeParameterDef>),
    /// Kind 4, field 2 (`TypeDef.form`).
    TypeDefForm(sley_ssmc::TypeDefForm),
    /// Kind 4, field 3 (`TypeDef.invariants`).
    TypeDefInvariants(EntityIdSet),
    /// Kind 4, field 4 (`TypeDef.visibility`).
    TypeDefVisibility(sley_ssmc::Visibility),
    /// Kind 5, field 1 (`Function.type_parameters`).
    FunctionTypeParameters(Vec<sley_ssmc::TypeParameterDef>),
    /// Kind 5, field 2 (`Function.parameters`).
    FunctionParameters(Vec<EntityId>),
    /// Kind 5, field 3 (`Function.result_type`).
    FunctionResultType(sley_ssmc::TypeExpr),
    /// Kind 5, field 4 (`Function.effects`).
    FunctionEffects(EntityIdSet),
    /// Kind 5, field 5 (`Function.entry_block`).
    FunctionEntryBlock(EntityId),
    /// Kind 5, field 6 (`Function.blocks`).
    FunctionBlocks(Vec<EntityId>),
    /// Kind 5, field 7 (`Function.contracts`).
    FunctionContracts(EntityIdSet),
    /// Kind 5, field 8 (`Function.visibility`).
    FunctionVisibility(sley_ssmc::Visibility),
    /// Kind 6, field 1 (`Parameter.owner`).
    ParameterOwner(EntityId),
    /// Kind 6, field 2 (`Parameter.role`).
    ParameterRole(sley_ssmc::ParameterRole),
    /// Kind 6, field 3 (`Parameter.ordinal`).
    ParameterOrdinal(u32),
    /// Kind 6, field 4 (`Parameter.value_type`).
    ParameterValueType(sley_ssmc::TypeExpr),
    /// Kind 7, field 1 (`Block.function`).
    BlockFunction(EntityId),
    /// Kind 7, field 2 (`Block.parameters`).
    BlockParameters(Vec<EntityId>),
    /// Kind 7, field 3 (`Block.operations`).
    BlockOperations(Vec<EntityId>),
    /// Kind 7, field 4 (`Block.terminator`).
    BlockTerminator(sley_ssmc::Terminator),
    /// Kind 7, field 5 (`Block.reachability`).
    BlockReachability(sley_ssmc::Reachability),
    /// Kind 8, field 1 (`Operation.block`).
    OperationBlock(EntityId),
    /// Kind 8, field 2 (`Operation.ordinal`).
    OperationOrdinal(u32),
    /// Kind 8, field 3 (`Operation.opcode`).
    OperationOpcode(u32),
    /// Kind 8, field 4 (`Operation.operands`).
    OperationOperands(Vec<sley_ssmc::ValueRef>),
    /// Kind 8, field 5 (`Operation.result_types`).
    OperationResultTypes(Vec<sley_ssmc::TypeExpr>),
    /// Kind 8, field 6 (`Operation.immediate`).
    OperationImmediate(sley_ssmc::Immediate),
    /// Kind 9, field 1 (`Constant.value`).
    ConstantValue(sley_ssmc::ConstValue),
    /// Kind 10, field 1 (`GlobalValue.value_type`).
    GlobalValueValueType(sley_ssmc::TypeExpr),
    /// Kind 10, field 2 (`GlobalValue.initializer`).
    GlobalValueInitializer(EntityId),
    /// Kind 10, field 3 (`GlobalValue.visibility`).
    GlobalValueVisibility(sley_ssmc::Visibility),
    /// Kind 11, field 1 (`EffectDef.effect_kind`).
    EffectDefEffectKind(sley_ssmc::EffectKind),
    /// Kind 11, field 2 (`EffectDef.scope_type`).
    EffectDefScopeType(sley_ssmc::TypeExpr),
    /// Kind 11, field 3 (`EffectDef.request_type`).
    EffectDefRequestType(sley_ssmc::TypeExpr),
    /// Kind 11, field 4 (`EffectDef.response_type`).
    EffectDefResponseType(sley_ssmc::TypeExpr),
    /// Kind 11, field 5 (`EffectDef.failure_type`).
    EffectDefFailureType(sley_ssmc::TypeExpr),
    /// Kind 11, field 6 (`EffectDef.visibility`).
    EffectDefVisibility(sley_ssmc::Visibility),
    /// Kind 12, field 1 (`CapabilityRequirement.effect`).
    CapabilityRequirementEffect(EntityId),
    /// Kind 12, field 2 (`CapabilityRequirement.allowed_scopes`).
    CapabilityRequirementAllowedScopes(Vec<sley_ssmc::ConstValue>),
    /// Kind 12, field 3 (`CapabilityRequirement.constraint_contracts`).
    CapabilityRequirementConstraintContracts(EntityIdSet),
    /// Kind 13, field 1 (`Contract.target`).
    ContractTarget(EntityId),
    /// Kind 13, field 2 (`Contract.contract_kind`).
    ContractContractKind(sley_ssmc::ContractKind),
    /// Kind 13, field 3 (`Contract.predicate`).
    ContractPredicate(EntityId),
    /// Kind 13, field 4 (`Contract.bindings`).
    ContractBindings(Vec<sley_ssmc::ContractBinding>),
    /// Kind 13, field 5 (`Contract.resource_limits`).
    ContractResourceLimits(Option<sley_ssmc::ResourceLimits>),
    /// Kind 14, field 1 (`TestCase.target`).
    TestCaseTarget(EntityId),
    /// Kind 14, field 2 (`TestCase.inputs`).
    TestCaseInputs(Vec<sley_ssmc::ConstValue>),
    /// Kind 14, field 3 (`TestCase.effect_environment`).
    TestCaseEffectEnvironment(sley_ssmc::EffectEnvironment),
    /// Kind 14, field 4 (`TestCase.expected`).
    TestCaseExpected(sley_ssmc::ExpectedOutcome),
    /// Kind 14, field 5 (`TestCase.observations`).
    TestCaseObservations(Vec<sley_ssmc::ExpectedObservation>),
    /// Kind 14, field 6 (`TestCase.resource_limits`).
    TestCaseResourceLimits(sley_ssmc::ResourceLimits),
    /// Kind 15, field 1 (`AdapterImport.adapter_id`).
    AdapterImportAdapterId([u8; 32]),
    /// Kind 15, field 2 (`AdapterImport.abi_version`).
    AdapterImportAbiVersion(u32),
    /// Kind 15, field 3 (`AdapterImport.request_type`).
    AdapterImportRequestType(sley_ssmc::TypeExpr),
    /// Kind 15, field 4 (`AdapterImport.response_type`).
    AdapterImportResponseType(sley_ssmc::TypeExpr),
    /// Kind 15, field 5 (`AdapterImport.failure_type`).
    AdapterImportFailureType(sley_ssmc::TypeExpr),
    /// Kind 15, field 6 (`AdapterImport.effects`).
    AdapterImportEffects(EntityIdSet),
    /// Kind 16, field 1 (`EntryPoint.function`).
    EntryPointFunction(EntityId),
    /// Kind 16, field 2 (`EntryPoint.exposure`).
    EntryPointExposure(EntryExposure),
    /// Kind 17, field 1 (`PolicyBinding.subject`).
    PolicyBindingSubject(EntityId),
    /// Kind 17, field 2 (`PolicyBinding.requirements`).
    PolicyBindingRequirements(EntityIdSet),
    /// Kind 18, field 1 (`DependencyBinding.dependency_root`).
    DependencyBindingDependencyRoot(StateRoot),
    /// Kind 18, field 2 (`DependencyBinding.external_package`).
    DependencyBindingExternalPackage(EntityId),
    /// Kind 18, field 3 (`DependencyBinding.local_namespace`).
    DependencyBindingLocalNamespace(EntityId),
}

impl FieldValue {
    /// Returns the exact `(entity_kind, field_tag)` selected by this value.
    #[must_use]
    pub const fn field_key(&self) -> (u16, u16) {
        match self {
            Self::WorkspacePackages(..) => (1, 1),
            Self::WorkspaceRootNamespace(..) => (1, 2),
            Self::WorkspaceCapabilityRequirements(..) => (1, 3),
            Self::WorkspaceContracts(..) => (1, 4),
            Self::WorkspaceTests(..) => (1, 5),
            Self::PackageWorkspace(..) => (2, 1),
            Self::PackageRootNamespace(..) => (2, 2),
            Self::PackageDependencies(..) => (2, 3),
            Self::PackageExports(..) => (2, 4),
            Self::NamespaceParent(..) => (3, 1),
            Self::NamespaceMembers(..) => (3, 2),
            Self::TypeDefTypeParameters(..) => (4, 1),
            Self::TypeDefForm(..) => (4, 2),
            Self::TypeDefInvariants(..) => (4, 3),
            Self::TypeDefVisibility(..) => (4, 4),
            Self::FunctionTypeParameters(..) => (5, 1),
            Self::FunctionParameters(..) => (5, 2),
            Self::FunctionResultType(..) => (5, 3),
            Self::FunctionEffects(..) => (5, 4),
            Self::FunctionEntryBlock(..) => (5, 5),
            Self::FunctionBlocks(..) => (5, 6),
            Self::FunctionContracts(..) => (5, 7),
            Self::FunctionVisibility(..) => (5, 8),
            Self::ParameterOwner(..) => (6, 1),
            Self::ParameterRole(..) => (6, 2),
            Self::ParameterOrdinal(..) => (6, 3),
            Self::ParameterValueType(..) => (6, 4),
            Self::BlockFunction(..) => (7, 1),
            Self::BlockParameters(..) => (7, 2),
            Self::BlockOperations(..) => (7, 3),
            Self::BlockTerminator(..) => (7, 4),
            Self::BlockReachability(..) => (7, 5),
            Self::OperationBlock(..) => (8, 1),
            Self::OperationOrdinal(..) => (8, 2),
            Self::OperationOpcode(..) => (8, 3),
            Self::OperationOperands(..) => (8, 4),
            Self::OperationResultTypes(..) => (8, 5),
            Self::OperationImmediate(..) => (8, 6),
            Self::ConstantValue(..) => (9, 1),
            Self::GlobalValueValueType(..) => (10, 1),
            Self::GlobalValueInitializer(..) => (10, 2),
            Self::GlobalValueVisibility(..) => (10, 3),
            Self::EffectDefEffectKind(..) => (11, 1),
            Self::EffectDefScopeType(..) => (11, 2),
            Self::EffectDefRequestType(..) => (11, 3),
            Self::EffectDefResponseType(..) => (11, 4),
            Self::EffectDefFailureType(..) => (11, 5),
            Self::EffectDefVisibility(..) => (11, 6),
            Self::CapabilityRequirementEffect(..) => (12, 1),
            Self::CapabilityRequirementAllowedScopes(..) => (12, 2),
            Self::CapabilityRequirementConstraintContracts(..) => (12, 3),
            Self::ContractTarget(..) => (13, 1),
            Self::ContractContractKind(..) => (13, 2),
            Self::ContractPredicate(..) => (13, 3),
            Self::ContractBindings(..) => (13, 4),
            Self::ContractResourceLimits(..) => (13, 5),
            Self::TestCaseTarget(..) => (14, 1),
            Self::TestCaseInputs(..) => (14, 2),
            Self::TestCaseEffectEnvironment(..) => (14, 3),
            Self::TestCaseExpected(..) => (14, 4),
            Self::TestCaseObservations(..) => (14, 5),
            Self::TestCaseResourceLimits(..) => (14, 6),
            Self::AdapterImportAdapterId(..) => (15, 1),
            Self::AdapterImportAbiVersion(..) => (15, 2),
            Self::AdapterImportRequestType(..) => (15, 3),
            Self::AdapterImportResponseType(..) => (15, 4),
            Self::AdapterImportFailureType(..) => (15, 5),
            Self::AdapterImportEffects(..) => (15, 6),
            Self::EntryPointFunction(..) => (16, 1),
            Self::EntryPointExposure(..) => (16, 2),
            Self::PolicyBindingSubject(..) => (17, 1),
            Self::PolicyBindingRequirements(..) => (17, 2),
            Self::DependencyBindingDependencyRoot(..) => (18, 1),
            Self::DependencyBindingExternalPackage(..) => (18, 2),
            Self::DependencyBindingLocalNamespace(..) => (18, 3),
        }
    }
}

/// Closed proposal value before any candidate record exists.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ProposalValue {
    /// One complete entity body.
    EntityBody(EntityBodyValue),
    /// One exact entity-body field.
    Field(FieldValue),
}
