[package]
name = "sley-vm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Sley 2 deterministic derived bytecode and reference VM."

[dependencies]
sley-check = { path = "../sley-check" }
sley-id = { path = "../sley-id" }
sley-ssmc = { path = "../sley-ssmc" }

[lints]
workspace = true
