[package]
name = "sley-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[[bin]]
name = "scb1_decoder"
path = "targets/scb1_decoder.rs"

[[bin]]
name = "schema_bootstrap_decoder"
path = "targets/schema_bootstrap_decoder.rs"

[dependencies]
sley-scb1 = { path = "../crates/sley-scb1" }
sley-schema = { path = "../crates/sley-schema" }
