[package]
name = "sley-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Sley 2 immutable SCB1 object store."

[dependencies]
sley-id = { path = "../sley-id" }
sley-scb1 = { path = "../sley-scb1" }

[lints]
workspace = true
