#!/usr/bin/env python3
"""Check the full S20-340 generated mutation-schema package."""

from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GENERATOR_PATH = ROOT / "scripts/generate_mutation_schema.py"


def read(relative: str) -> str:
    return (ROOT / relative).read_text(encoding="utf-8")


def load_generator():
    spec = importlib.util.spec_from_file_location("sley2_mutation_codegen", GENERATOR_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load mutation schema generator")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


problems: list[str] = []
check = subprocess.run(
    [sys.executable, str(GENERATOR_PATH), "--check"],
    cwd=ROOT,
    check=False,
    capture_output=True,
    text=True,
)
if check.returncode != 0:
    problems.append(f"generated output drift: {(check.stderr or check.stdout).strip()}")

generator = load_generator()
entities, enum_names = generator.parse_manifest(generator.MANIFEST.read_bytes())
operations = generator.build_operations(entities, enum_names)
generated = read("crates/sley-mutate/src/generated.rs")
api = read("crates/sley-mutate/src/lib.rs")
schema = read("crates/sley-schema/src/lib.rs")
spec_text = read("docs/spec/MUTATION_SCHEMA_V1.md")
work_packages = read("docs/WORK_PACKAGES.md")
cargo = read("Cargo.toml")
makefile = read("Makefile")

classes = {operation.class_name for operation in operations}
keys = {
    (operation.class_name, operation.target_kind, operation.field_tag)
    for operation in operations
}
field_count = sum(len(entity.fields) for entity in entities)
typed_replacements = sum(
    operation.class_name == "ReplaceTypedField" for operation in operations
)

if len(entities) != 18 or [entity.tag for entity in entities] != list(range(1, 19)):
    problems.append("generated entity set is not the closed 1..18 set")
if len(classes) != 16:
    problems.append("generated mutation class set does not contain exactly sixteen classes")
if len(operations) != 179:
    problems.append(f"generated concrete operation count drifted from 179 to {len(operations)}")
if len(keys) != len(operations):
    problems.append("generated operation keys are not unique")
if typed_replacements != field_count:
    problems.append("complete typed-field replacement coverage is missing")

for token in [
    "Status: S20-340 normative schema-generation specification.",
    "all eighteen entity kinds",
    "exactly these sixteen classes",
    "ExpectedIdentityAbsent",
    "ExactEntityVersion",
    "ExactContainerVersion",
    "S20-340 supplies schema input to S20-350 only",
]:
    if token not in spec_text:
        problems.append(f"mutation spec missing {token!r}")

for token in [
    "// @generated by scripts/generate_mutation_schema.py; DO NOT EDIT.",
    generator.EXPECTED_BLAKE3,
    "pub const ENTITY_SCHEMAS",
    "pub const MUTATION_OPERATIONS",
]:
    if token not in generated:
        problems.append(f"generated artifact missing {token!r}")

for token in [
    "pub enum MutationClass",
    "pub enum PreimageRequirement",
    "pub enum FieldMutationShape",
    "pub struct FieldSchemaDescriptor",
    "pub struct EntitySchemaDescriptor",
    "pub struct MutationOperationDescriptor",
    "generated_schema_reproduces_the_frozen_manifest_digest",
    "all_eighteen_entity_kinds_are_closed_and_ordered",
    "all_sixteen_mutation_classes_are_present_and_tagged",
]:
    if token not in api:
        problems.append(f"mutation API/test surface missing {token!r}")

for token in ["SSMC1_EPOCH1_MANIFEST", "SSMC1_EPOCH1_MANIFEST_BLAKE3"]:
    if token not in schema:
        problems.append(f"schema manifest export missing {token!r}")

for forbidden in [
    "pub fn apply",
    "pub fn decode",
    "pub fn import",
    "CandidateId",
    "WorkspaceId",
    "PolicyRootId",
    "CapabilityToken",
    "std::fs",
    "std::env",
    "std::net",
    "std::process",
    "SystemTime",
]:
    if forbidden in api or forbidden in generated:
        problems.append(f"forbidden executable/ambient mutation surface present: {forbidden}")

# `StateRoot` is an exact canonical field type string on DependencyBinding; it
# may appear in generated metadata but must not become an authority-bearing API.
if "StateRoot" in api:
    problems.append("forbidden state-root authority present in handwritten mutation API")

if '"crates/sley-mutate"' not in cargo:
    problems.append("sley-mutate is absent from the Cargo workspace")
if "python3 scripts/check_mutation_schema.py" not in makefile:
    problems.append("routine quick gate omits the mutation schema checker")
if "full epoch-1 immutable mutation descriptors" not in work_packages:
    problems.append("S20-340 work-package closeout is absent")

result = {
    "contract": "s20-340-mutation-schema-v1",
    "schema_manifest_blake3": generator.EXPECTED_BLAKE3,
    "entity_kinds": len(entities),
    "entity_fields": field_count,
    "mutation_classes": len(classes),
    "concrete_operations": len(operations),
    "typed_field_replacements": typed_replacements,
    "candidate_construction": False,
    "runtime_mutation": False,
    "nabu_review": "REVISE_TO_FULL_IMMUTABLE_DESCRIPTOR_CODEGEN",
    "problems": problems,
    "result": "PASS" if not problems else "FAIL",
}
print(json.dumps(result, indent=2, sort_keys=True))
raise SystemExit(0 if not problems else 1)
