#!/usr/bin/env python3
"""Generate the closed S20-350a mutation proposal host-value model."""

from __future__ import annotations

import argparse
import hashlib
import re
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "docs/spec/SSMC1_EPOCH1_SCHEMA.txt"
OUTPUT = ROOT / "crates/sley-mutate/src/value_generated.rs"
EXPECTED_SHA256 = "d0a3097c4d62cf5812934932cb18c2b55a6f7beddda1cf2c3092715706aa0918"
EXPECTED_BLAKE3 = "044d21d328e40d517fd09fd099c9697fbba2c95d0a519eade333c1140d648e73"

ENTITY_RE = re.compile(r"^entity ([0-9]+) ([A-Za-z][A-Za-z0-9]*) ([A-Za-z][A-Za-z0-9]*)$")
RECORD_RE = re.compile(r"^record ([A-Za-z][A-Za-z0-9]*)\((.*)\)$")


@dataclass(frozen=True)
class Field:
    tag: int
    name: str
    value_type: str
    required: bool


@dataclass(frozen=True)
class Entity:
    tag: int
    name: str
    body_name: str
    fields: tuple[Field, ...]


def split_top_level(value: str) -> list[str]:
    if not value:
        return []
    parts: list[str] = []
    start = 0
    depth = 0
    for index, char in enumerate(value):
        if char == "<":
            depth += 1
        elif char == ">":
            depth -= 1
            if depth < 0:
                raise ValueError(f"unbalanced generic close in {value!r}")
        elif char == "," and depth == 0:
            parts.append(value[start:index])
            start = index + 1
    if depth != 0:
        raise ValueError(f"unbalanced generic expression in {value!r}")
    parts.append(value[start:])
    return parts


def parse_field(raw: str) -> Field:
    tag_raw, name, typed = raw.split(":", 2)
    if not typed or typed[-1] not in "!?":
        raise ValueError(f"field requiredness is not explicit in {raw!r}")
    return Field(int(tag_raw), name, typed[:-1], typed[-1] == "!")


def parse_manifest(raw: bytes) -> list[Entity]:
    if hashlib.sha256(raw).hexdigest() != EXPECTED_SHA256:
        raise ValueError("canonical manifest changed: update frozen review and digest pins")
    records: dict[str, tuple[Field, ...]] = {}
    entity_rows: list[tuple[int, str, str]] = []
    for line in raw.decode("utf-8").splitlines():
        if match := RECORD_RE.fullmatch(line):
            fields = tuple(parse_field(part) for part in split_top_level(match[2]))
            if [field.tag for field in fields] != list(range(1, len(fields) + 1)):
                raise ValueError(f"record {match[1]} field tags are not closed and ascending")
            records[match[1]] = fields
        if match := ENTITY_RE.fullmatch(line):
            entity_rows.append((int(match[1]), match[2], match[3]))
    if [row[0] for row in entity_rows] != list(range(1, 19)):
        raise ValueError("entity tags must be exactly 1 through 18")
    entities = [Entity(tag, name, body, records[body]) for tag, name, body in entity_rows]
    if sum(len(entity.fields) for entity in entities) != 75:
        raise ValueError("entity-body field inventory must remain exactly 75")
    return entities


def generic_arg(value: str, head: str) -> str | None:
    prefix = f"{head}<"
    if value.startswith(prefix) and value.endswith(">"):
        return value[len(prefix) : -1]
    return None


def rust_type(value: str) -> str:
    if inner := generic_arg(value, "List"):
        return f"Vec<{rust_type(inner)}>"
    if inner := generic_arg(value, "Set"):
        if inner != "EntityId":
            raise ValueError(f"no closed canonical set host type for {value}")
        return "EntityIdSet"
    if inner := generic_arg(value, "Option"):
        return f"Option<{rust_type(inner)}>"
    primitives = {
        "Bool": "bool",
        "Bytes": "Vec<u8>",
        "F32": "u32",
        "F64": "u64",
        "FixedBytes32": "[u8; 32]",
        "SInt": "i64",
        "Text": "String",
        "UInt16": "u16",
        "UInt32": "u32",
        "UInt64": "u64",
        "EntityId": "EntityId",
        "StateRoot": "StateRoot",
        "EntryExposure": "EntryExposure",
    }
    if value in primitives:
        return primitives[value]
    return f"sley_ssmc::{value}"


def rust_field_type(field: Field) -> str:
    value_type = rust_type(field.value_type)
    return value_type if field.required else f"Option<{value_type}>"


def pascal(value: str) -> str:
    return "".join(piece[:1].upper() + piece[1:] for piece in value.split("_"))


def render(entities: list[Entity]) -> str:
    digest_bytes = ", ".join(
        f"0x{EXPECTED_BLAKE3[index:index + 2]}" for index in range(0, 64, 2)
    )
    lines = [
        "// @generated by scripts/generate_mutation_value_codecs.py; DO NOT EDIT.",
        f"// source: docs/spec/SSMC1_EPOCH1_SCHEMA.txt; blake3-256: {EXPECTED_BLAKE3}",
        "",
        "/// BLAKE3-256 of the exact canonical schema manifest used for host values.",
        f"pub const VALUE_HOST_SOURCE_SCHEMA_BLAKE3: [u8; 32] = [{digest_bytes}];",
        "/// Closed entity-body host-value count.",
        f"pub const ENTITY_BODY_VALUE_COUNT: usize = {len(entities)};",
        "/// Closed entity-body field-value count.",
        f"pub const FIELD_VALUE_COUNT: usize = {sum(len(entity.fields) for entity in entities)};",
        "",
    ]
    for entity in entities:
        lines.extend([
            f"/// Closed proposal-only body for entity kind {entity.tag} (`{entity.name}`).",
            "#[derive(Clone, Debug, Eq, PartialEq)]",
            f"pub struct {entity.body_name} {{",
        ])
        for field in entity.fields:
            lines.extend([
                f"    /// Exact manifest field {field.tag} (`{field.name}`).",
                f"    pub {field.name}: {rust_field_type(field)},",
            ])
        lines.extend(["}", ""])

    lines.extend([
        "/// Closed typed value for one complete SSMC1 entity body.",
        "#[derive(Clone, Debug, Eq, PartialEq)]",
        "pub enum EntityBodyValue {",
    ])
    for entity in entities:
        lines.extend([
            f"    /// Entity kind {entity.tag} (`{entity.name}`).",
            f"    {entity.name}({entity.body_name}),",
        ])
    lines.extend([
        "}",
        "",
        "impl EntityBodyValue {",
        "    /// Returns the exact closed SSMC1 entity-kind tag.",
        "    #[must_use]",
        "    pub const fn kind_tag(&self) -> u16 {",
        "        match self {",
    ])
    for entity in entities:
        lines.append(f"            Self::{entity.name}(..) => {entity.tag},")
    lines.extend(["        }", "    }", "}", ""])

    lines.extend([
        "/// Closed typed value for one exact SSMC1 entity-body field.",
        "#[derive(Clone, Debug, Eq, PartialEq)]",
        "pub enum FieldValue {",
    ])
    for entity in entities:
        for field in entity.fields:
            variant = f"{entity.name}{pascal(field.name)}"
            lines.extend([
                f"    /// Kind {entity.tag}, field {field.tag} (`{entity.name}.{field.name}`).",
                f"    {variant}({rust_field_type(field)}),",
            ])
    lines.extend([
        "}",
        "",
        "impl FieldValue {",
        "    /// Returns the exact `(entity_kind, field_tag)` selected by this value.",
        "    #[must_use]",
        "    pub const fn field_key(&self) -> (u16, u16) {",
        "        match self {",
    ])
    for entity in entities:
        for field in entity.fields:
            variant = f"{entity.name}{pascal(field.name)}"
            lines.append(f"            Self::{variant}(..) => ({entity.tag}, {field.tag}),")
    lines.extend(["        }", "    }", "}", ""])

    lines.extend([
        "/// Closed proposal value before any candidate record exists.",
        "#[derive(Clone, Debug, Eq, PartialEq)]",
        "pub enum ProposalValue {",
        "    /// One complete entity body.",
        "    EntityBody(EntityBodyValue),",
        "    /// One exact entity-body field.",
        "    Field(FieldValue),",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if committed output differs")
    args = parser.parse_args()
    generated = render(parse_manifest(MANIFEST.read_bytes()))
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit(
                "generated mutation value host model drift: run scripts/generate_mutation_value_codecs.py"
            )
        return 0
    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
